TracecatHQ/tracecat

- frontend/src/components/auth/login.tsx
- frontend/src/lib/auth.ts
- frontend/src/providers/session.tsx
- frontend/src/utils/supabase/client.ts
- frontend/src/utils/supabase/middleware.ts
- tracecat/auth.py
- Use parent `__aenter__` in `AuthenticatedServiceClient`
Closes #31
> fix: Reference backend API domain dynamically for frontend client/server components

- frontend/src/app/settings/credentials/page.tsx
- frontend/src/app/settings/layout.tsx
- frontend/src/components/confirmation-dialog.tsx
- frontend/src/components/new-credential-dialog.tsx
- frontend/src/lib/secrets.ts
- frontend/src/types/schemas.ts
- tests/test_auth.py
- tests/test_templates.py
- tracecat/api/app.py
- tracecat/auth.py
- tracecat/db.py
- tracecat/runner/templates.py
- tracecat/types/api.py
- tracecat/types/secrets.py
- Update the `Secret` schema so that each can contain an arbitrary number of key-value pairs. For example, you could define a 'github_secret' that can contain 'GH_ACCESS_TOKEN', 'GH_USERNAME' etc. This makes supporting complex auth/secret types (e.g. OAuth) easier down the line.
- Update the encryption corresponding to the above change. We encrypt the entire keys list as a JSON object, and store the encrypted secret as bytes (same as before).
- Update the credentials page in the settings to reflect the schema changes. The creation wizard has also been updated to accept >=1 key-value pairs.
- Update templated secret parsing in the execution engine and updated tests.
- Ran updated tests, `test_templates.py` tests passing.
- Manual workflow run which calls URLScan API with successful console …
> feat(ui+engine): Extend secrets manager

- frontend/src/types/schemas.ts
- tests/test_integrations.py
- tracecat/concurrency.py
- tracecat/db.py
- tracecat/integrations/_registry.py
- tracecat/integrations/example.py
- tracecat/integrations/utils.py
- tracecat/logger.py
- tracecat/messaging/producer.py
- tracecat/runner/actions.py
- tracecat/secrets/README.md
- tracecat/secrets/__init__.py
- tracecat/secrets/helpers.py
- tracecat/types/actions.py
- Allow secrets to be declared in the `@registry.register()` decorator
- The key-value pairs inside each secret (that's added from the frontend) are loaded dynamically into each integration function call.
- See secrets/README.md for more details
> feat: Integrate secrets manager with integration functions

- docker-compose.override.yaml
- docker-compose.prod.yaml
- docker-compose.yaml
- docs/installation.mdx
- services.sh
Closes #47. Updated `services.sh` to parse the desired runtime environment.
`dev` mode uses bind mounts with your host machine `frontend/node_modules` and `frontend/.next` to sync host/container. This requires running `pnpm install` inside of `/frontend`, then using the commands below:
- Start `./services.sh start ...` 
- Stop `./services.sh stop ...` 
This is suitable for local development.
`prod` mode bypasses running `pnpm install` on the host, suitable for quick preview use cases.
- Start `./services.sh start --env prod ...`
- Stop `./services.sh stop --env prod ...`
- Add option to force rebuild images using `--no-cache` flag.
I would rather have used `pnpm start` to override the start command, but doing so seems to change some hidden config inside of posthog and supabase that isn't …
> build: Split dev and prod into separate run options

- services.sh
Make installation even more seamless
- Reuse the python docker image that's used in our services config to generate an ephermeral container that creates a fernet key
Runs locally
> build: Generate Fernet key using ephemeral Docker container during installation

- .env.example
- frontend/src/types/schemas.ts
- tracecat/integrations/datadog.py
- tracecat/types/actions.py
Closes part of tracker issue #67
Note: still untested. Requires an AWS-Datadog lab environment (with stratus-red-team to generator signals).
> feat(engine+ui): Add Datadog security signals actions

- frontend/src/components/badges.tsx
- frontend/src/components/cases/columns.tsx
- frontend/src/components/cases/data/categories.tsx
- frontend/src/components/cases/panel-content.tsx
- frontend/src/components/flair.tsx
- frontend/src/lib/cases.ts
- frontend/src/providers/case-panel.tsx
- tracecat/api/app.py
- Implement change case status
> feat: Implement change case status controls

- frontend/src/components/workspace/catalog/action-catalog.tsx
- Add vertical line to demarcate `groupItem`s. Results in a more organized look.
> feat(ui): Add clearer hierarchical style

- tracecat/api/app.py
- tracecat/runner/app.py
We had a user report that sending a malformed paylaod returned a user-facing stacktrace. In order to suppress this, we can add a catch-all exception handler for our public api endpoints
```
❯ curl -X POST "https://REDACTED.ngrok-free.app/webhook/REDACTED" -H "Content-type: application/json"
Internal Server Error
```
```
❯ curl -X POST "https://REDACTED.ngrok-free.app/webhook/REDACTED"" -H "Content-type: application/json"
{"message":"An unexpected error occurred. Please try again later."}
```
With the change, return a well-formed http response
> feat(engine): Suppress stack traces using catch-all handler

- tests/conftest.py
- tests/test_integrations.py
- tracecat/concurrency.py
- tracecat/config.py
- tracecat/runner/actions.py
After upgrading to loguru, integration would throw an error regarding `multiprocessing.SimpleQueue` when the execution is offloaded to a child process. 
Realizations: when using cloudpickle, it captures the function + imported modules. This also captures the loguru logger, which (most likely) has a queue object it uses for async writes. 
Remove multiprocessing
> fix: Remove multiprocessing for run integration action

- tracecat/actions/core/cases.py
- tracecat/api/app.py
- tracecat/contexts.py
- tracecat/dsl/dispatcher.py
- tracecat/dsl/workflow.py
- tracecat/logging/_logger.py
- tracecat/registry.py
- tracecat/types/api.py
- tracecat/types/cases.py
- Added `tracecat.contexts.ctx_run` 
- Pass contextvars through `workflow` and `activity` args, as activities may be run on different workers (no longer threadlocal). The alternative is passing context through Temporal header interceptors, but appears to be more work.
- Revived case management
- Fix propagation of `ContextVars` throughout Temporal workflows and workers (tested using case management)
> fix: Run context propagation

- tests/unit/test_template_expressions.py
- tracecat/templates/expressions.py
- tracecat/templates/patterns.py
- Implement inline function calling in template expressions
- Invoke this using the `FNS` context like such:
```
${{ FNS.less_than(ACTIONS.path.to.value, int(5)) }}
${{ FNS.less_than(ACTIONS.path.to.value, int(5)) -> str }}
```
- We never call `eval` as part of this implementation
- We only allow a strict subset of values and use a very simple subset of builtin functions
This is a prerequisite to having conditional execution.
- Added relevant tests
- All tests/unit/test_template_expressions.py passing
> feat(engine): Implement template expression functions

- pyproject.toml
- tests/conftest.py
- tests/integration/test_workflows.py
- tests/unit/test_auth.py
- tests/unit/test_graph.py
- tests/unit/test_sandbox.py
- tests/unit/test_workflows.py
- tracecat/api/app.py
- tracecat/auth/clients.py
- tracecat/auth/credentials.py
- tracecat/auth/sandbox.py
- tracecat/cli/config.py
- tracecat/cli/dev.py
- tracecat/cli/workflow.py
- tracecat/contexts.py
- tracecat/db/converters.py
- tracecat/db/helpers.py
- tracecat/db/schemas.py
- tracecat/dsl/common.py
- tracecat/dsl/dispatcher.py
- tracecat/dsl/graph.py
- tracecat/dsl/workflow.py
- tracecat/registry.py
- tracecat/templates/__init__.py
- tracecat/types/api.py
- tracecat/types/cases.py
- You can now use templated secret expressions `${{ SECRETS.my_secret.SECRET_KEY }}` just as you would regular template expressions. These are now compatible with the Temporal backend. 
- Extend `AuthSandbox` to allow the sandbox target to be either 'env' or 'context', the first is standard behavior which loads secrets into the environment, the latter loads it into a dictionary
- Removed `AuthenticatedRunnerClient`
- Refactor auth module
- Refactor DSL module
- Added `pytest-mock` and unit tests
> feat(engine): Implement JIT secrets for template secret expressions

- docs/api-reference/reference/triggers/create-webhook.mdx
- docs/api-reference/reference/triggers/delete-webhook.mdx
- docs/api-reference/reference/triggers/get-webhook.mdx
- docs/api-reference/reference/triggers/list-webhooks.mdx
- docs/api-reference/reference/triggers/update-webhook.mdx
- docs/api-reference/reference/udfs/get-udf.mdx
- docs/api-reference/reference/udfs/validate-udf-args.mdx
- docs/api-reference/reference/workflows/update-workflow.mdx
- docs/mint.json
- docs/openapi.yml
- frontend/src/components/workspace/canvas/canvas.tsx
- frontend/src/components/workspace/panel/trigger-panel.tsx
- frontend/src/lib/auth.ts
- frontend/src/lib/hooks.ts
- frontend/src/lib/trigger.ts
- frontend/src/lib/workflow.ts
- frontend/src/providers/builder.tsx
- tests/unit/test_template_expressions.py
- tracecat/api/app.py
- tracecat/auth/credentials.py
- tracecat/auth/sandbox.py
- tracecat/cli/_config.py
- tracecat/cli/workflow.py
- tracecat/db/helpers.py
- tracecat/dsl/common.py
- `workflows/{wfid}/commit` now accepts a yaml file in the request body
- Since we only have 1 webhook we use `/webhook` instead of `/webhooks` and just return the object instead of a list of webhooks
- Use PATCH to update workflows
- Removed delete webhook endpoint as webhook cannot be deleted manually, only when workflow gets deleted.
- Remove list webhooks accordingly
- Update CLI to use `workflows/{wfid}/commit` instead creating the workflow definition direcly -- aligned with how you would do it with pure api calls
- Changed no-auth mode to use hardcoded secret token instead of service key
- Rename updateDndFlow to udpateWorkflowGraphObject
- Add missing changes for `pydantic.SecretStr` usage + update tests
- Ran commands in terminal
- Triggered kite workflow with slack, works
> feat: Webhook API changes

- tests/data/workflows/unit_transform_forwarder_loop.yml
- tests/data/workflows/unit_transform_forwarder_loop_expected.yml
- tests/unit/test_expressions.py
- tests/unit/test_workflows.py
- tracecat/dsl/workflow.py
- tracecat/expressions/__init__.py
- tracecat/expressions/engine.py
- tracecat/expressions/eval.py
- tracecat/registry.py
- Add action-local context `var`. Usage: `var.my_var`. Lowercase denotes that it's action-local, meaning that no other action in the workflow can see it
- Implement for loops through the `for_each` clause. Write a generator-like expression `${{ for var.x in INPUTS.some.iterable }}`
- These features now allow any action to map over an iterable collection. Every action has a `for_each` clause, and when bound to an action-local variable like `var.x`, you can access the iterator value through `var.x`.
- All unit tests passing
- Added action-local expression tests
- Added tests/data/workflows/unit_transform_forwarder_loop.yml
> feat(engine): Implement action-local `var` context  + iterable `for_each` clause

- tests/data/workflows/unit_transform_forwarder_zip.yml
- tests/data/workflows/unit_transform_forwarder_zip_expected.yml
- tests/unit/test_workflows.py
- tracecat/dsl/common.py
- tracecat/dsl/workflow.py
- tracecat/expressions/engine.py
- Allow passing a list of expressions into `for_each` clause. Zips the iterables under the hood
- Note:Lists must have the same length otherwise an exception is thrown.
- Added new correctness workflow test, passing
> feat(engine): Implement for_each zip expression

- tests/data/workflows/unit_transform_forwarder_map_loop.yml
- tests/data/workflows/unit_transform_forwarder_map_loop_expected.yml
- tests/unit/test_expressions.py
- tests/unit/test_workflows.py
- tracecat/expressions/engine.py
- tracecat/expressions/functions.py
- tracecat/expressions/patterns.py
- tracecat/expressions/validators.py
- Implement list literals. Use square brackets with comma delimited inner expressions
-  Improve nested structure parsing
- You can now call `FN.func.map(arg1, arg2)` to call `FN.func` on the arguments.
- If any arguments are iterable (ignoring str and bytes), take note of these.
- Non-iterable values get applied `itertools.repeat` (broadcast).
- The final iterables are zipped.
- Iteration stops when the shortest iterable is exhausted
- For examples, see the unit tests
- Remove unused pattern factory
- Added expression unit tests for map, list literal + test workflow of "nested loop" processing using `for_each` and `.map`
> feat(engine): Implement FN.func.map

- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/src/components/workspace/canvas/canvas.tsx
- frontend/src/components/workspace/catalog/udf-catalog.tsx
- tests/unit/test_graph.py
- tracecat/api/app.py
- tracecat/db/converters.py
- tracecat/db/schemas.py
- tracecat/dsl/common.py
- tracecat/dsl/graph.py
- tracecat/types/cases.py
- tracecat/utils.py
- Move initla graph construction to server side
- Workflow commit endpoint now performs graph object construction
- Add layouting using dagre
- Clean up `RFGraph API`, prepare to take on more server side logic
- Unit tests all passing
> feat(engine): Generate graph from headless mode

- tests/unit/test_workflows.py
- tracecat/dsl/worker.py
- tracecat/dsl/workflow.py
- Instead of displaying `run_udf` for every function, dynamically wrap each UDF in a Temporal activity and register it with workers.
- In the UDF key we replace `.` with `__`. e.g. `ns.subns.method_name` -> `ns__subns__method_name`
- Improve workflow observability
- Before we start a worker, generate temporal activity wrappers for all registered UDFs so that they show up as activity types in the Temporal UI
- All workflow tests passing
> feat(engine): Dynamically register UDFs in DSLActivities

- tracecat/db/converters.py
- tracecat/dsl/graph.py
- Add better error message for empty graph
- Use `RFGraph.action_nodes()` instead of `RFGraph.nodes` to perform validation
- Verified that workflow that was created headless can be edited in the GUI, then committed back as a definition. Cross referenced this with database
> fix: Incorrect reference to all nodes instead of action nodes only

- docs/openapi.yml
- tracecat/api/app.py
- tracecat/cli/workflow.py
- tracecat/dsl/common.py
- tracecat/registry.py
- tracecat/types/api.py
- Perform UDF args validation on workflow commit
- The API returns the error details in the response
- Updated OpenAPI docs according to commit workflow API changes
```
❯ tracecat workflow commit wf-3ffb4a86e05d4db3a178393ac786bcf5 -f playbooks/aws/guardduty-to-slack.yml
Failed to commit to workflow 'wf-3ffb4a86e05d4db3a178393ac786bcf5'!
{
'workflow_id': 'wf-3ffb4a86e05d4db3a178393ac786bcf5',
'status': 'failure',
'message': 'Validation errors',
'errors': [
{
'ok': False,
'message': 'Error validating integrations.aws.guardduty.list_guardduty_alerts',
'detail': [
{
'type': 'datetime_from_date_parsing',
'loc': ['start_time', "ValidationInfo(config={'title': 'IntegrationsAwsGuarddutyListGuarddutyAlerts', 'extra_fields_behavior': 'forbid'}, context=None, data={}, field_name='start_time')"], …
```
> feat(engine): Implement server-side UDF args validation on commit

- .github/release-drafter.yml
- .github/workflows/playbooks.yml
- .github/workflows/tests.yml
- playbooks/alert_management/aws-guardduty-to-slack.yml
- playbooks/alert_management/datadog-siem-to-slack.yml
- tests/integration/test_playbooks.py
- tracecat/cli/_config.py
This is an incomplete PR. Need to deal with accessing docker / localhost from within github actions issues in a follow-up PR.
- Assumes no data is sent to webhook
- Need to extend this test suite to support playbooks with incoming data into the trigger
- Need to extend this test suite with scheduled workflows
> ci: Add draft GH workflow to test all playbooks

- .env.example
- .github/workflows/build-push-images.yml
- .github/workflows/tests.yml
- Dockerfile
- tests/unit/test_cli.py
- tracecat/cli/_config.py
The Tracecat API image is big (~1.2gb). Don't use it just for the CLI. You need the server to use the CLI anyway.
> ci: Add ui to ghcr and entrypoint to cli

- .github/workflows/tests.yml
- tests/unit/test_cli.py
- tracecat/cli/workflow.py
- tracecat/db/engine.py
- We were still relying on the `newUserFlow` to create the default user in the GUI
- Now with headless mode, we should just create this user directly
> feat(engine): Create default user in headless mode on db start

- pyproject.toml
- tracecat/actions/integrations/edr/crowdstrike.py
[falconpy](https://github.com/CrowdStrike/falconpy) is the official CS client from CS. Fully unit tested, robust support, and actively maintained.
> feat(integrations): Migrate crowdstrike integrations to falconpy

- .github/workflows/playbooks.yml
- .github/workflows/test-python.yml
- tracecat/logging/_logger.py
- Tracecat logger reads from `LOG_LEVEL` env var
- Update CI pytests
> ci: Configure logger verbosity

- pyproject.toml
- tests/data/workflows/unit_runtime_test_adder_tree.yml
- tests/data/workflows/unit_runtime_test_adder_tree_expected.yml
- tests/data/workflows/unit_runtime_test_chain.yml
- tests/data/workflows/unit_runtime_test_chain_data.json
- tests/data/workflows/unit_runtime_test_chain_expected.yml
- tests/unit/test_workflows.py
- tracecat/api/app.py
- tracecat/cli/workflow.py
- tracecat/dsl/common.py
- tracecat/dsl/graph.py
- tracecat/dsl/workflow.py
- tracecat/types/headers.py
```yaml
tests:
- ref: pull_crowdstrike_alerts
enable: true # default: true
validate_args: true # default: true
success: # This is the mocked/patched output for the action.
failure: # TODO
config:
enable_runtime_tests: true
```
- Adds new top-level workflow directive `tests`
- Define a list of `tests` that mock the output value of actions at runtime
- By default, all tests defined are enabled. You can control whether they're enabled or disabled at runtime.
- You can override any action with any data structure
- You can load mock data using `fsspec` compliant uris/paths
- Add custom headers module
- Pass `--test` (CLI) or X-Tracecat-Enable-Runtime-Tests: true` (http) to enable runtime action tests
- At execution time, for incoming webhooks we check for `X-Tracecat-Enable-Runtime-Tests` …
> feat(engine): Implement runtime action tests

- tests/unit/test_cli.py
- tracecat/cli/workflow.py
- You can now commit a YAML workflow definition as part of the create cli command: `tracecat workflow create --commit <path>`
- Added unit tests
- All tests passing
> feat(cli): Add --commit flag in tracecat workflow create

- .github/workflows/test.yml
- playbooks/alert_management/aws-guardduty-to-cases.yml
- tests/integration/test_playbooks.py
- tracecat/cli/workflow.py
- Ignore secrets creation fixture errors (to deal with local development case when secrets have already been created and clash)
- Replaced create workflows CLI commands in test with direct calls to the REST API via the private create and activate workflow functions
- That function returns a json with workflow ID under the id field
- Replaced inputs with triggers in AWS guardduty to slack playbook
> test: Fix flaky `workflow_id` parse in playbooks test

- frontend/src/components/workspace/canvas/trigger-node.tsx
- frontend/src/components/workspace/panel/trigger-panel.tsx
- frontend/src/types/schemas.ts
- playbooks/alert_management/aws-guardduty-to-slack.yml
- tracecat/api/app.py
- tracecat/auth/credentials.py
- tracecat/cli/_utils.py
- tracecat/cli/dev.py
- tracecat/cli/main.py
- tracecat/cli/schedule.py
- tracecat/cli/workflow.py
- tracecat/config.py
- tracecat/contexts.py
- tracecat/db/schemas.py
- tracecat/dsl/dispatcher.py
- tracecat/dsl/schedules.py
- tracecat/dsl/workflow.py
- tracecat/identifiers/__init__.py
- tracecat/identifiers/schedules.py
- tracecat/identifiers/workflow.py
- tracecat/types/api.py
- Implement Schedule CRUD operations for API
- Schedule implemented as a top-level entity in our schema
- Implement Schedule CRUD operations for CLI
- Schedules are backed by Temporal schedules under the hood, and CRUD operations are coordinated between our and Temporal's systems
- Update schedules UI
- Added more utility functions the CLI
- Set `TEMPORAL__CLUSTER_QUEUE` inside `tracecat.config`
- Add better visibility for 422 errors with a FastAPI exception handler
- Use `slack` instead of `slack_channel` for aws GD playhbook
- Manual QA for schedules
- Verified that crud works and syncs with Tamporal
> feat(engine): Implement schedules

- tracecat/actions/core/email.py
- tracecat/actions/core/llm.py
- tracecat/actions/integrations/cdr/amazon_guardduty.py
- tracecat/actions/integrations/cdr/microsoft_defender.py
- tracecat/actions/integrations/cdr/wiz.py
- tracecat/actions/integrations/chat/slack.py
- tracecat/actions/integrations/edr/crowdstrike.py
- tracecat/actions/integrations/edr/microsoft_defender.py
- tracecat/actions/integrations/edr/sentinel_one.py
- tracecat/actions/integrations/enrichment/abuseipdb.py
- tracecat/actions/integrations/enrichment/alienvault.py
- tracecat/actions/integrations/enrichment/censys.py
- tracecat/actions/integrations/enrichment/emailrep.py
- tracecat/actions/integrations/enrichment/hybrid_analysis.py
- tracecat/actions/integrations/enrichment/malwarebazaar.py
- tracecat/actions/integrations/enrichment/pulsedive.py
- tracecat/actions/integrations/enrichment/shodan.py
- tracecat/actions/integrations/enrichment/urlscan.py
- tracecat/actions/integrations/enrichment/virustotal.py
- tracecat/actions/integrations/siem/datadog.py
- tracecat/actions/integrations/siem/elastic.py
- tracecat/registry.py
- tracecat/types/secrets.py
- Implement and use `RegistrySecret` in place of a `list[str]` for registry secrets
- Add `SecretName` and `SecretKey` patterns for runtime pattern validation
- Add docstrings with example usage
- ⁠Single source of truth for what secrets are required
- ⁠⁠Solves documentation: colocates it directly with the UDF, and is easier to automate updating docs
- ⁠⁠Declarative and obvious to the user
- ⁠⁠Better for validation as it’s all contained in the udf registry, no need to parse the actual funciton body to look for env vars
- Enforce secret name and key patterns
> feat(udf): Improve registry secrets api

- tracecat/dsl/worker.py
- Use asyncio eager task factory for worker event loop
- Improve asyncio performance on coroutines that can complete before being scheduled on the event loop
- https://github.com/python/cpython/issues/104144
- Backed by data from Instagram: https://github.com/python/cpython/issues/97696
> perf(engine): Use asyncio eager task factory for worker event loop

- docker-compose.dev.yml
- playbooks/alert_management/aws-guardduty-to-slack.yml
- playbooks/alert_management/datadog-extract-email-to-slack.yml
- tests/data/workflows/integration_send_slack.yml
- tests/data/workflows/unit_transform_filter_dict.yml
- tests/data/workflows/unit_transform_filter_dict_expected.yml
- tests/data/workflows/unit_transform_filter_function.yml
- tests/data/workflows/unit_transform_filter_function_expected.yml
- tests/unit/test_expressions.py
- tests/unit/test_functions.py
- tests/unit/test_workflows.py
- tracecat/actions/core/transform.py
- tracecat/actions/integrations/chat/slack.py
- tracecat/config.py
- tracecat/dsl/common.py
- tracecat/dsl/dispatcher.py
- tracecat/dsl/workflow.py
- tracecat/expressions/functions.py
- tracecat/expressions/parser/evaluator.py
- tracecat/expressions/parser/grammar.py
- tracecat/expressions/parser/validator.py
- tracecat/expressions/shared.py
- tracecat/expressions/validation.py
- Add depends_on validity checks
- dd strict flag for eval_jsonpath, defaults to false
- Add custom filter function as action and function expression. 
- This allows you to do more complex filtering, for example you can express these kinds of filtering semantics: 
- "filter a collection of items using a jsonpath pointing to a field in this item, and use a function/operator for evaluation/comparison" 
- You can use double quotes for string literals
- Add dump run results to fs for debugging
- New actions
- `core.transfrom.filter`: wrapper around `custom_filter`
- `core.transform.build_reference_table`: Allows you to convert a list of objects into a dict, where you choose the key using a jsonpath
- Add time related function expressions: FN.now, FN.minutes
- Add workflow start_time into ENV …
> feat: Update Datadog extract emails to slack playbook + add new transform actions

- pyproject.toml
- tracecat/actions/etl/extraction/email.py
Fixes #246. This sacrifices performance for SIMD heavy queries. But we have yet to fully leverage polars ETL in Tracecat (yet). Will push this temporary fix first.
- Build two images: one with `polars` and another with `polars-lts-cpu`
- Create docker compose extension for users without AVX
> build(engine): Replace `polars` with `polars-lts-cpu`

- frontend/src/app/workflows/[workflowId]/executions/event-details.tsx
- frontend/src/app/workflows/[workflowId]/executions/event-history.tsx
- frontend/src/app/workflows/[workflowId]/executions/nav.tsx
- frontend/src/client/schemas.gen.ts
- frontend/src/client/services.gen.ts
- frontend/src/client/types.gen.ts
- frontend/src/components/icons.tsx
- frontend/src/lib/event-history.ts
- frontend/src/lib/jsonschema.ts
- tests/conftest.py
- tests/data/workflows/unit_child_workflow_child.yml
- tests/data/workflows/unit_child_workflow_parent.yml
- tests/data/workflows/unit_child_workflow_parent_expected.yml
- tests/unit/test_workflows.py
- tracecat/actions/__init__.py
- tracecat/actions/core/workflow.py
- tracecat/api/app.py
- tracecat/dsl/common.py
- tracecat/dsl/schedules.py
- tracecat/dsl/worker.py
- tracecat/dsl/workflow.py
- tracecat/expressions/eval.py
- tracecat/registry.py
- tracecat/types/api.py
- tracecat/workflow/definitions.py
- tracecat/workflow/executions.py
- tracecat/workflow/models.py
- tracecat/workflow/service.py
- Implement basic child workflow invocation
- Add event history for child workflows + UI
- Implement looping for child workflows
- Child workflow loops run at the temporal workflow level
- Udfs still run loop iteration inside the temporal activity
- Implement `all` and `isolated` fail strategies using `asyncio.gather` / `GatheringTaskGroup`
- Implement `parallel`, `sequential`, and `batched` loop strategies
- Implement `returns` key for `DSLInput`. Pass an expression to define the return value of the workflow.
- Break `workflow/service.py` into `workflow/definitions.py` and `workflow/executions.py`
- Refator some models to avoid circular imports
- Standardize colors to avoid confusion
- Added new workflow test
```yaml
title: Parent workflow
description: Test child workflow
entrypoint: …
```
> feat: Implement child workflow core functionality

- tracecat/actions/integrations/edr/__init__.py
- tracecat/actions/integrations/edr/sentinel_one.py
This adds additional actions to the existing Sentinel One integration:
- Agent lookup by hostname
- Agent lookup by username
- Isolate endpoint
- Unisolate endpoint
These are common response actions for an EDR product; as an example, based on an alert, you could lookup a hostname or username to find which machines they are active on, then isolate those which would block all connections except the communication channel that the EDR tool uses to communicate with it's control plane.
No open issues for this
N/A
I tested this by creating a workflow that looked up an agent, performed an isolation, and then performed an unisolation and confirmed in Sentinel One that all actions took place correctly.
> Add new SentinelOne actions: lookup by username, hostname, isolate, unisolate

- tracecat/actions/integrations/iam/__init__.py
- tracecat/actions/integrations/iam/okta.py
Okta API calls do not always accept supplying the user's ID using the profile.login value.  Added a new action to lookup user(s) by login/email and modified other actions to take Okta user id as input.
Tested against live Okta environment
> Okta enhancement/fix

- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/src/components/workspace/canvas/canvas.tsx
- frontend/src/components/workspace/canvas/custom-handle.tsx
- frontend/src/components/workspace/canvas/selector-node.tsx
- frontend/src/components/workspace/canvas/trigger-node.tsx
- frontend/src/components/workspace/canvas/udf-node.tsx
- frontend/src/components/workspace/catalog/udf-catalog.tsx
- frontend/src/components/workspace/panel/workspace-panel.tsx
- frontend/src/lib/workflow.ts
- frontend/src/providers/builder.tsx
- Make node handles larger, but visually the same size (transparent body with dot). Easier to grab and drag, also nice because it looks like its floating.
- Add node silhouette when dragging out from an edge
- When the above completes, react flow fires the `onConnectEnd` event. We capture this and drop a selector (placeholder) node in which you can browse UDFs. On selection (click/hit enter), the selector node then replaces itself with the selected node type
- Add esc keybind to remove ephemeral nodes
- I call these kinds of non-concrete nodes "ephemeral nodes". We do not persist their state, and whenever we update the backend graph we defensively filter out any ephermeral nodes.
- The backend doesn't need to know about the existence of ephermeral nodes
> feat(ui): Improve node handles + add node silhouette + add selector node

- tracecat/actions/integrations/iam/__init__.py
- tracecat/actions/integrations/iam/okta.py
- Added new action: list_okta_user_events
- Renamed find_okta_user to find_okta_users since we return a list, the name is more communicative of the return type
N/A
N/A
Tested against live API.
> Added list_okta_user_events; Renamed find_okta_user to find_okta_users

- .github/workflows/deploy-to-aws.yml
- aws/app.py
- aws/tracecat_cdk/fargate.py
Fixes issue with worker establishing a connection to Temporal.
- Drop service connect for worker and temporal server
- Add internal facing ALB to Fargate stack
- Added listeners and target (with protocolVersion=GRPC) for temporal service
- Update backend security group to allow traffic to internal ALB
- A Record: Created to point `temporal.{API_DOMAIN_NAME}` to the ALB.
- CNAME record: `temporal` subdomain to the API hosted zone
- Certificate: ACM certificate created for `temporal` subdomain added to the public API hosted zone
- gRPC Target Group: Configured for the Temporal service with gRPC protocol.
- gRPC target only supports listeners with HTTPS protocol
- Can only create certificates programmatically via CDK for public hosted zones
- Even though hosted zone is public, traffic is all …
> ci(infra): [Part 1 / 2] Add internal ALB to direct fargate traffic to temporal

- frontend/src/lib/api.ts
- Previously when the `__PLACEHOLDER_API_URL__` string doesn't get replaced, axios would think that this is a string path and direct api calls to `localhost:3000/__PLACEHOLDER_API_URL__`
> fix: Check API_URL against the placeholder string instead of nullish

- docker-compose.dev.yml
- docker-compose.yml
- tracecat/actions/core/cases.py
- tracecat/api/app.py
- tracecat/db/engine.py
- tracecat/types/api.py
- tracecat/workflow/definitions.py
- tracecat/workflow/executions.py
- Move fastapi exception handlers to app creation
- Remove clone workflow
- Remove global db `engine` variable in app router. We instead use the global variable inside the `db.engine` module and use methods to access the connection pool
- Make all api router usage of db session through fastapi's dependency injection subsystem
- Added `API_URL` to `docker-compose.yml`
- This is in preparation for introducing `asyncpg` and to break up the app router into smaller routers.
- Also tested that the exception handlers can catch errors in sub-routers (which apparently couldn't do before)
> refactor(engine): Standardize db access + clean up api

- pyproject.toml
- tests/conftest.py
- tests/unit/test_expressions.py
- tracecat/actions/core/cases.py
- tracecat/api/routers/actions.py
- tracecat/api/routers/cases/actions.py
- tracecat/api/routers/cases/contexts.py
- tracecat/api/routers/cases/management.py
- tracecat/api/routers/public/callbacks.py
- tracecat/api/routers/public/dependencies.py
- tracecat/api/routers/public/webhooks.py
- tracecat/api/routers/schedules.py
- tracecat/api/routers/secrets.py
- tracecat/api/routers/udfs.py
- tracecat/api/routers/users.py
- tracecat/api/routers/validation.py
- tracecat/db/engine.py
- tracecat/db/schemas.py
- tracecat/dsl/workflow.py
- tracecat/secrets/service.py
- tracecat/types/validation.py
- tracecat/validation.py
- tracecat/workflow/executions/models.py
- tracecat/workflow/executions/router.py
- tracecat/workflow/executions/service.py
- tracecat/workflow/management/definitions.py
- tracecat/workflow/management/management.py
- tracecat/workflow/management/models.py
- tracecat/workflow/management/router.py
- Add `asyncpg` postgresdb driver. Better synergy with fastapi and has better performance (see the benchmark on `asyncpg` 's readme)
- We're maintaining backward compatibility by keeping the sync sqlmodel engine
- Adopted async db sessions across all services and routers
- Add pytest fixture to share single event loop across a test session. This was causing a bug where a future was awaited on a different event loop (i.e. the event loop changed)
- Added deduplication for `ValidationResult` objects
- DB connection and session is sensitive to the event loop, as the connection pool is a global var.
- There are issues with how pytest handles async-marked tests. We've used the fixture to share the same event loop over all the tests, however in the FastAPI lifespan we cannot switch out the sync …
> feat(engine): Add asyncpg

- .env.example
- Caddyfile
- docker-compose.dev.yml
- docker-compose.yml
- Add Caddyfile to point http://localhost to UI service and http://localhost/api/ (with prefix stripping via handle path directive) to API service
- Add `BASE_DOMAIN` and `ADDRESS` env vars to docker-compose and .env.example
- Update public URLs in .env.example to the Caddy exposed URLs
- Specified internal routes for temporal and API in caddy
- Removed docker network configs in docker compose
- Style: just rearranged docker fields to be consistent between services (e.g. `restart` after `container_name`)
- !!! Removed overly verbose `tracecat_` prefix from container names
- Test on both `docker compose up` and `docker compose -f docker-compose.dev.yml up`
- Go to http://localhost (UI)
- Go to http://localhost/api/ (API)
- QA loop:
1. Retrieve workflows
2. Create new workflow
3. Add case …
> ci(infra): Add Caddy as reverse proxy

- tracecat/api/routers/public/webhooks.py
Append /wait to a standard webhook to wait for the response of the workflow to return.  The final_context of the workflow will be returned as the response to the initial POST.
N/A
N/A
Call a webhook by appending /wait and the response should be the final_context of the workflow you called.
> Synchronous calling of webhooks

- tracecat/dsl/common.py
- Raise `TracecatValidationError` when workflow is committed without error. This gets shown on the UI nicely.
> feat(engine): Improve user facing error when workflow is committed without any actions

- tests/unit/test_expressions.py
- tracecat/expressions/parser/evaluator.py
- tracecat/expressions/parser/grammar.py
- tracecat/expressions/parser/validator.py
- Extend Lark grammar to use recurvie `jsonpath_expression`
- Reason aboue jsonpaths as path segments of `ATTRIBUTE_ACCESS` and `BRACKET_ACCESS`
- attribute access: `.cname`, `.'some_key'`, `.['bracket']`
- bracket access: `['key']`, `[*]` (array wildcard), `[\d+]` (array index)
- These changes also allow for repeated bracket access application: `.segment['key1']['key2']` (equivalent to .segment.key1.key2 if object, if array then it will index)
- Added relevant expression unit tests
- Add test to check that we can use leading underscores for attribute access
> fix(engine): Allow object/attribute access for jsonpath

- tests/unit/test_expressions.py
- tracecat/expressions/functions.py
- tracecat/expressions/parser/evaluator.py
- Tines returns `None` by default if no match
- Enables simpler checking of present/absent fields with just truthy/falsy comparison or comparison with `None`
- Make `ExprEvaluator` not strict by default. 
- Make `eval_jsonpath` return `None` literal over empty list when strict=False
- Updated expression unit tests to reflect new defaults + changes
> feat(engine): Make ExprEvaluator not strict by default and eval jsonpath return None literal

- env-migration.sh
- Add `env-migration.sh`
- This will prompt the user to create a copy of the existing `.env` file, and then overwrite contents of `.env`.
1. Creates a timestamped backup of your current `.env` file.
2. Reads your existing `.env` file and the new `.env.example`.
3. Creates a new `.env` file based on the `.env.example` structure.
4. Preserves values from your old `.env` for keys that exist in the new template.
5. Adds new keys from the template (with empty values) if they didn't exist in your old `.env`.
6. Ignores keys from your old `.env` that don't exist in the new template.
> **Note:** This script will overwrite your current `.env` file, but a backup is always created first.
> You will be asked for confirmation before any changes are made.
1. Place this script in the same directory as …
> feat: Add env-migration script

- frontend/src/client/schemas.gen.ts
- frontend/src/client/services.gen.ts
- frontend/src/client/types.gen.ts
- frontend/src/components/nav/workbench-nav.tsx
- tracecat/workflow/management/router.py
- Add endpoint `/workflows/{workflow_id}/export` to return workflow definition json file
- Add button (ellipsis) to workbench navbar to export as json
- This exports the workflow definition row from the db as json
- Updated openapi-ts client
- Able to download json file and view contents and verified correctness
> feat(engine+ui): Add export workflow json in workbench

- tracecat/api/app.py
- tracecat/auth/users.py
- We were counting workspaces that the current user (default admin) is a member, but we just want to count all workspaces
- Change logic to use admin api to check for any workspaces. Only create default workspace if none.
- Similarly for the default admin user, creation relied on a matching email not being there. Now we only create it if there are no users. Use an internal admin role to construct the workspace
Manual testing and verification by observing DB
> fix(engine): Fixes default workspace and admin creation issues on startup

- docs/self-hosting/authentication/google.mdx
- docs/self-hosting/authentication/introduction.mdx
Should be `google_oauth` and not just `google` for `TRACECAT__AUTH_TYPES`. See `.env.example`
> docs: Use `google_oauth` over `google` in docs

- frontend/src/components/nav/workbench-nav.tsx
- frontend/src/components/workbench/panel/trigger-panel.tsx
- See commit messages
- Also the default DiaglogContent component's width is wider
Now (~25% wider)
> refactor(ui): Remove inactive properties in schedules table

- frontend/src/components/nav/workbench-nav.tsx
- tracecat/types/validation.py
- Issue where passing lists and dicts cause this to fail. Band aid fix just by stringifying using json.dumps 
- The above error occurred when i tried to commit a playbook i imported from yaml, and we try to deduplicate the validation errors returned to the user
> fix(engine): Hash unhashable types using json dumps during validation

- frontend/src/components/dashboard/create-workflow-button.tsx
- frontend/src/components/dashboard/dashboard-table.tsx
- frontend/src/components/nav/workbench-nav.tsx
- frontend/src/lib/export.ts
- frontend/src/lib/hooks.ts
- playbooks/alert_management/aws-guardduty-to-cases.yml
- playbooks/alert_management/aws-guardduty-to-slack.yml
- playbooks/alert_management/crowdstrike-to-cases-no-slack.yml
- playbooks/alert_management/crowdstrike-to-cases.yml
- playbooks/alert_management/datadog-to-cases.yml
- playbooks/alert_management/sentinel-one-to-slack.yml
- playbooks/alert_management/slack-to-crowdstrike-update.yml
- playbooks/alert_management/slack-to-sentinel-one-update.yml
- playbooks/enrichment/tag-user-in-slack-scheduled.yml
- playbooks/enrichment/tag-user-in-slack.yml
- playbooks/enrichment/triage-using-llms.yml
- playbooks/threat_intel/virustotal-to-email.yml
- tests/data/workflows/playbook_virustotal_email.yml
- tests/unit/test_cli.py
- tracecat/workflow/management/management.py
- tracecat/workflow/management/models.py
- tracecat/workflow/management/router.py
- Add import from json
- Improve import/export logic
- Add `ExternalWorkflowDefintion`. This will serve as a portable format for workflows outside of the platform. Helps lay foundation for 2way sync (if we wish to support that in the future)
- This class carries additional metadata alongside just the DSL workflow definition (which is what our YAMLs previously were). This lets you export out a workflow with, and restore it using the same workflow id so you can keep the run history.
- Update workflow definitions to have a top level `definition` key
- Can export yaml
- Can export json
- Can import yaml
- API
- UI
- Can import json
- API
- UI
- Can run imported yaml workflow
- Can run imported json workflow
- Verify that workflow ID can be overridden
- Verify that if fields not passed, are …
> feat(engine+ui): Import/export from json/yaml

- frontend/src/app/workspaces/[workspaceId]/workflows/[workflowId]/executions/page.tsx
- frontend/src/app/workspaces/layout.tsx
- frontend/src/components/executions/event-details.tsx
- tracecat/dsl/workflow.py
- tracecat/types/exceptions.py
- Add typing for TracecatException detail
- Fix loguru `KeyError: 'type'` when passing f-strings with curly braces. This is a known loguru limitation based on how it handles string formatting/interpolation
- Update workflow runs UI to be more consistent with rest of UI
- Add toggle collapse for json viewer
- Separate out error.message and error.stack_trace in the UI for better readability 
https://github.com/user-attachments/assets/817e1b04-e0a8-43a4-ac04-cef9bcc4dd76
> feat(engine+ui): Improve error messages [1/N]

- tracecat/auth/credentials.py
Fixes issue where newly promoted admin users were seeing 403 forbidden when trying to access a workspace they're not members of.
> fix(engine): Allow admin users to view new workspaces

- playbooks/virustotal-quickstart.yml
- tests/playbooks/test_playbooks.py
- tests/unit/test_sandbox.py
- tracecat/auth/sandbox.py
- Add live playbook testing infra
- Added virustotal playbook from quickstart to run in the above
- Extend `AuthSandbox._get_secrets` to get db secrets through the service layer instead of making an api call
- Updated auth sandbox tests for the above change
Manual QA 
- After the above changes, we're still able to get secrets from our SM
- Updated pytest tests passing
> test(engine): Add live playbook testing infra and VT playbook

- frontend/src/components/workspaces/edit-workspace-secret.tsx
- tracecat/auth/sandbox.py
- tracecat/secrets/router.py
- tracecat/secrets/service.py
- Fixed issue where `AuthSandbox` with `context` target doesn't load all secrets
- Fixed issue where form validation occured message would appear on editing a secret
- Simplify update secret form logic. Make the form mirror the update secret endpoint as closely as possible - omitted fields are not changed, only update fields that are specified  
- Add info text to indicate whether a field will be changed
Manual QA, confirm that able to edit secrets and use in workflows correctly
https://github.com/user-attachments/assets/55e82545-0a64-413b-9c45-77c91c3c8d79
> fix(engine+ui): Fix unable to update secrets

- tracecat/actions/integrations/edr/crowdstrike.py
Added a new integration which can fetch detection details by passing in the detection IDs.
When querying for CrowdStrike detections, an array of detection IDs are returned. Currently, there is no integration which allows you to use these IDs and query for detection details. This integration simply takes the array of IDs and returns the full detection details.
Sample Use Case:
Sample Configuration:
1. Verify the code is valid
2. Create a workflow using the List CrowdStrike Detects and the new Get CrowdStrike Detect Summaries integrations
3. Validate that an array of detection details is returned
> feat(integration): Add list crowdstrike detections summary

- docker-compose.dev.yml
- docker-compose.yml
- tracecat/actions/__init__.py
- tracecat/actions/etl/normalization/__init__.py
- tracecat/actions/etl/normalization/ecs.py
- tracecat/actions/integrations/__init__.py
- Added integration to elastic ingest pipeline REST API
- Namespaced action as `etl.normalization.normalize_events_to_ecs`
- Uses "events" as the common terminology for any JSON input / output / logs emitted or received by Tracecat actions
- Added elasticsearch (with security mode off) to docker compose stacks
- To do in: #378
> feat(integration): Normalize events to ECS

- tests/unit/test_secrets.py
- tests/unit/test_workflows.py
- tracecat/config.py
- tracecat/dsl/workflow.py
- tracecat/secrets/common.py
- tracecat/secrets/constants.py
- tracecat/workflow/executions/service.py
- Fix JSONDecodeError in run history
- Add secret masking in udf inputs/outputs
- Add environment variable `TRACECAT__UNSAFE_DISABLE_SM_MASKING` to toggle masking secrets. We don't expose this in .env.example.
Invariants or non-negotiables
- Any secret values returned by UDFs will be fully masked
- If you try to use a result that involves a secret value, you will receive the masked value
- This is intentional, as otherwise we are crossing a security boundary
- The only secure method of retrieving secrets is using the SM inside an integration or secret expression.
> feat(engine): Mask secrets

- tracecat/actions/core/http.py
- tracecat/dsl/workflow.py
> feat(integrations): Capture ReadTimeout exceptions in httpx as "expected" errors

- frontend/src/client/schemas.gen.ts
- frontend/src/client/types.gen.ts
- frontend/src/components/executions/event-details.tsx
- tests/unit/test_workflows.py
- tracecat/dsl/common.py
- tracecat/dsl/worker.py
- tracecat/dsl/workflow.py
- tracecat/types/exceptions.py
- tracecat/workflow/executions/models.py
- tracecat/workflow/executions/service.py
- tracecat/workflow/management/models.py
- tracecat/workflow/schedules/bridge.py
- tracecat/workflow/schedules/models.py
- tracecat/workflow/schedules/router.py
- tracecat/workflow/schedules/service.py
- Introduce concepts of `pull` and `push` based dispatch types for workflows
- What we have right now are push based workflows. We pass a `DSLInput` into the `DSLWorkflow` args, and the workflow executes it. 
- We introduce pull based workflows - we don't pass `DSLInput` or trigger inputs into workflow args. The workflow then makes a call to find the latest workflow definition and latest trigger inputs in `Schedule` table.
- All new schedules created will be `pull` based. Existing schedules are unchanged.
- Make schedules pull based
- They pull the latest workflow defintion
- They pull the latest trigger input payload  in `Schedule.inputs`
- Add `TracecatNotFoundError` and `TracecatServiceError` for abstraction of 
- Add UI to update the current trigger inputs. I've tested that the …
> feat+refactor(engine): Pull based workflows for schedules + general schedule improvements

- playbooks/tutorials/limacharlie/list_tags.yml
- playbooks/tutorials/limacharlie/run_investigation.yml
- playbooks/tutorials/limacharlie/run_tests.yml
- tracecat/actions/core/http.py
- Support passing OAuth parameters into http core action
- API design inspired by Cribl collector templates and Tines OAuth2 credentials type
- Updated Limacharlie playbooks (set `token_response_key` to `token`)
> feat(integration): Support OAuth2 flows in http core action

- Dockerfile
- Dockerfile.dev
- templates/_example_hit_localhost_server.yml
- templates/_example_template_action.yml
- tests/unit/test_template_actions.py
- tracecat/dsl/workflow.py
- tracecat/expressions/parser/evaluator.py
- tracecat/expressions/parser/grammar.py
- tracecat/expressions/shared.py
- tracecat/registry.py
- Register a UDF from a templated action definition 
- You can think of these are wrappers around UDFs, that can provide additional functionality over plain udfs
- For example, this makes it easy to perform `reshape` after a regular UDF
- Introduce new action-local contexts (notice lowercase) `inputs` and `layers`
- Reference the UDF argments using `inputs`
- Action layers 
- A template action is composed of smaller layers, that are regular UDFs
- Layers are run sequentially, in the order it is defined in the `layers` list. The action-local context is updated with the each layer's result
- Reference a layer is by its `ref`. e.g. `ref: my_layer` -> `${{ layers.my_layer.result }}`
- Added some examples and tests that better showcase the functionality
- You cannot invoke the `var` context …
> feat(engine): Template actions first version

- .env.example
- Dockerfile
- Dockerfile.dev
- docker-compose.dev.yml
- docker-compose.yml
- pyproject.toml
- tests/conftest.py
- tests/data/workflows/unit_ordering_kite.yml
- tests/data/workflows/unit_ordering_kite2.yml
- tests/playbooks/test_playbooks.py
- tests/unit/test_registry.py
- tests/unit/test_template_actions.py
- tests/unit/test_workflows.py
- tracecat/actions/etl/__init__.py
- tracecat/config.py
- tracecat/registry.py
Loader component
- Update registry to register udfs from python modules
- Add functionality to dynamically import modules and their contained UDFs
- Add functionality to pull and register udfs from github (through pip)
- Improve control over registry lifecycle by decoupling 
- Fix template actions not invoking AuthSandbox
- Add metadata: is_template, origin
> feat(engine): Implement remote UDF registry [1/N]

- tracecat/dsl/models.py
We need a better way to manage registry versions.
> feat(engine+ui): Prevent users from configuring registry_version for now

- registry/tracecat_registry/_internal/models.py
- tracecat/validation.py
- `RegistrySecret.keys` remains as required keys
- Use `RegistrySecret.optional_keys` to define optional keys
> feat(engine): Add optional keys for registry secret

- frontend/src/components/workbench/panel/udf-panel.tsx
- tracecat/registry/actions/router.py
- tracecat/registry/client.py
- tracecat/registry/executor.py
- We weren't propagating errors properly across the HTTP boundary. 
- Fix spelling of 'Template Action'
> fix(engine): Better HTTP error propagation

- registry/tracecat_registry/templates/sentinel_one/get_agents_by_hostname.yml
- registry/tracecat_registry/templates/sentinel_one/get_agents_by_hostname_exact.yml
- registry/tracecat_registry/templates/sentinel_one/get_agents_by_username.yml
- registry/tracecat_registry/templates/sentinel_one/get_agents_by_username_exact.yml
- registry/tracecat_registry/templates/sentinel_one/get_firewall_rule.yml
- registry/tracecat_registry/templates/sentinel_one/isolate_agent.yml
- registry/tracecat_registry/templates/sentinel_one/list_alerts.yml
- registry/tracecat_registry/templates/sentinel_one/unisolate_agent.yml
- registry/tracecat_registry/templates/sentinel_one/update_alert_status.yml
- registry/tracecat_registry/templates/sentinel_one/update_firewall_rule.yml
The HTTP header for S1 integrations is `Authorization: ApiToken API_TOKEN_VALUE`. The current templates are missing the "ApiToken" prefix.
This PR add the ApiToken prefix.
> fix(integration): Add missing ApiKey to Authorization header

- Dockerfile
- tracecat/config.py
- tracecat/registry/actions/service.py
- tracecat/registry/repositories/router.py
- tracecat/registry/repository.py
- Fix permission error (no 13) when we install the remote github repo through `uv`
- Change ownership of certain directories that `uv` and `python` will use to load and import modules to `apiuser` when `APP_ENV=production`
> fix(engine): Fix repository not syncing in production docker compose builds

- alembic/env.py
- pyproject.toml
- tracecat/db/engine.py
Our current database connection handling doesn't adequately address potential connection failures, especially after the initial engine creation. This can lead to unexpected errors and poor user experience when database connections become stale or are interrupted. Additionally, we were using a deprecated method for executing queries with SQLModel.
Moreover, if the database password changes, we also cannot recover from a connection failure.
1. Updated both `get_session` and `get_async_session` functions to test the connection immediately after creation.
2. Implemented logic to recreate the engine if a connection test fails.
3. Replaced the deprecated `session.execute()` method with `session.exec()` for SQLModel compatibility.
4. Added retry decorators to `get_session_context_manager` and …
> fix(engine): Add retries to recreate DB engine if test conn raises an exception

- tracecat/validation.py
Closes #418 
Tested with blank http request, as seen above (requires 'url'). This was broken since registry was changed
> fix(engine): Fix action validation

- frontend/next-env.d.ts
- frontend/src/client/schemas.gen.ts
- frontend/src/client/types.gen.ts
- frontend/src/components/executions/event-details.tsx
- frontend/src/components/workbench/panel/udf-panel.tsx
- tracecat/dsl/action.py
- tracecat/dsl/constants.py
- tracecat/dsl/graph.py
- tracecat/dsl/models.py
- tracecat/dsl/workflow.py
- tracecat/types/api.py
- tracecat/workflow/executions/models.py
- tracecat/workflow/executions/service.py
- tracecat/workflow/management/management.py
- Add `ActionRetryPolicy` to configure maximum attempts (default: 1) and timeout (default: 300s)
- By default, the action will fail immediately unless max attempts is > 1
- If it's 0, will retry indefinitely (temporal semantics)
- Clean up some error handling logic in the run action activity as we transform the error in the registry client
- Manual testing with http action failing to hit endpoint
> feat: Add configurable action retries

- tracecat/dsl/workflow.py
- Factor in `start_delay` to the underlying `temporal` activity timeout. 
- IMO The timeout is the time granted for the activity to execute. If the activity is not executing and just waiting to start, it doesn't make sense to count this in the timeout.
- This won't change the timeout view in the UI. In the UI we use the action's retry policy - not temporals. Only temporal will see the new total value.
- This can help avoid possible bugs where accidental config of `start_delay` > `timeout` causes actions to not run anything
> fix(engine): Include start delay in total activity timeout

- registry/tracecat_registry/templates/crowdsec/search_ip_address.yml
Closes #461 
Missing `definition` key
- Add test that checks that all actions can be imported safely @topher-lo
> fix(integration): Incorrect template action format

- tracecat/workflow/executions/models.py
- Add default values to `EventGroup.start_delay` and `EventGroup.retry_policy`
> fix: Add defaults for retry_policy and start_delay for EventGroup

- frontend/src/components/workbench/canvas/custom-handle.tsx
- frontend/src/components/workbench/canvas/udf-node.tsx
https://github.com/user-attachments/assets/4768015d-3872-4e7c-80a1-36adb2ade0fd
Color scheme suggested by Claude:
```
In this code, the color choices appear to follow common UI/UX patterns for logical operations:
1. **Blue (bg-blue-500/80) for "ALL"**:
- Blue is often used to represent "AND" operations in logic gates and flow diagrams
- The color blue typically conveys reliability and completeness
- In this context, "ALL" means all inputs must be satisfied (logical AND)
2. **Amber/Orange (bg-amber-500/80) for "ANY"**:
- Amber/Orange is often used to represent "OR" operations
- It's a warmer color that suggests flexibility or alternative options
- In this context, "ANY" means any input can satisfy the condition (logical OR)
The `/80` suffix indicates 80% opacity, which gives a slightly …
```
> feat(ui): Update target handle to show join strategy

- frontend/src/components/workbench/canvas/action-node.tsx
- frontend/src/components/workbench/canvas/custom-handle.tsx
- frontend/src/components/workbench/canvas/trigger-node.tsx
Issue dragging out node because of the new join target node handle. Also made names mode explicit/clearer
> fix: Separate out source and target handles for different node types

- frontend/src/components/workbench/canvas/selector-node.tsx
Since we added autofocus, the node wouldn't delete on pressing `esc` when using react flow's useKeyPress
> fix(ui): Delete selector node when pressing esc even when focused

- frontend/src/components/workbench/panel/action-panel.tsx
- Add action panel tabs to split accordion into smaller chunks
- Add icons and tooltips to `type` and `origin` in the action description
- Align action icon to top left
https://github.com/user-attachments/assets/00e4d249-824e-465b-9b21-11888a8f7a70
> feat(ui): Add action panel tabs + cleanup action panel description section

- registry/tracecat_registry/integrations/checkpoint.py
- registry/tracecat_registry/integrations/limacharlie.py
- registry/tracecat_registry/integrations/microsoft_graph.py
- registry/tracecat_registry/integrations/wiz.py
Users will have to re-sync their `tracecat_registry` (maybe also restart their instances) to get the right grouping
> fix(integrations): Add missing display groups

- playbooks/tutorials/limacharlie/run_investigation.yml
- playbooks/tutorials/limacharlie/run_tests.yml
- tracecat/validation/common.py
- Fix issue where validating an expression string in a non-string type field would cause an unexpected validation error.
- Update broken playbooks tests for `core.http_request` default `method` field
> fix: Add missing TemplateValidator to dynamic expectation models

- frontend/src/client/services.gen.ts
- frontend/src/client/types.gen.ts
- frontend/src/components/registry/registry-repos-table.tsx
- tracecat/registry/repositories/router.py
- tracecat/registry/repositories/service.py
Closes #457
- Update registry repository delete endpoint to accept ID instead of origin
- Unblocking this so users can clear incorrect/accidental repo origins
- If you accidentally delete your main remote repository, you still have to restart your instance to reload it
> feat: Allow deletion of remote repository

- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/src/components/workbench/canvas/selector-node.tsx
Closes #429 .
- Override the default shadcn `Command` search and use `fuzzysort`
- Includes realtime highlighting of fuzzy-match components
- Allow scrolling over selector node area
https://github.com/user-attachments/assets/0e20025c-2524-4b95-9424-c3bb6f185ede
> feat(ui): Fuzzy selector node search

- frontend/src/components/workbench/panel/trigger-panel.tsx
- tracecat/workflow/schedules/models.py
- Remove trigger inputs from schedules UI
- We are keeping the backend for this for now for backward compatibility, but encourage users to move away from using `TRIGGER` when preparing inputs for schedules
> refactor: Remove trigger inputs from schedules UI

- tracecat/dsl/view.py
- Make `RFGraph.source_handle` nullable, such that we avoid when `sourceHandle` is returned as `null` from the FE in the trigger node.
> fix: Allow sourceHandle to be null for trigger

- frontend/src/client/schemas.gen.ts
- frontend/src/client/types.gen.ts
- frontend/src/components/workbench/panel/action-panel.tsx
- frontend/src/components/workbench/panel/trigger-panel.tsx
- tests/unit/test_export.py
- tests/unit/test_workflows.py
- tracecat/dsl/common.py
- tracecat/dsl/scheduler.py
- tracecat/dsl/view.py
- tracecat/workflow/management/management.py
- Enables multiple entrypoints, without the need for a no-op reshape node. Note that having multiple entrypoints causes the workflow to execute them concurrently.
(concurrent execution)
- Consolidate entrypoint logic in models
- Entrypoint in `DSLInput` still kept for backward compatiblity
- Remove entrypoint details in ui
> feat: Enable multiple workflow entrypoints

- registry/tracecat_registry/integrations/ldap3.py
With the refactoring to registry and removal of async, accessing _connection before it's instantiated throws an exception.  This ensures that it exists when the check is performed before binding.
Didn't open an issue, minor fix.
Using any of the functions provided by this integration would throw exceptions without this fix.
> fix(integration): Add sentinel value for LDAP connection attribute

- frontend/src/components/ui/skeleton.tsx
- frontend/src/components/workbench/canvas/action-node.tsx
- frontend/src/components/workbench/canvas/canvas.tsx
- frontend/src/components/workbench/canvas/selector-node.tsx
- frontend/src/components/workbench/canvas/trigger-node.tsx
- frontend/src/components/workbench/panel/action-panel.tsx
- frontend/src/components/workbench/panel/trigger-panel.tsx
- frontend/src/components/workbench/panel/workbench-panel.tsx
- frontend/src/lib/hooks.tsx
- frontend/src/lib/workflow.ts
- frontend/src/providers/builder.tsx
- tracecat/dsl/common.py
- tracecat/dsl/view.py
Fixes follow on issue to #515, where UI state now appeared correct and backend state becomes out of sync.
Solution was to only reference `action` table as source of truth and remove reliance on `Workflow.object`
- Reduce use of `RFGraph` values. Only use action ids to reference actions
- Remove use of `ActionNodeData` values. Only use `useAction` hooks to reference action data
- Cleanup unused/old code
- Improve node loading states
> feat+fix: Remove reliance on graph object data + improve node loading states

- registry/tracecat_registry/templates/crowdstrike/get_detections.yml
- registry/tracecat_registry/templates/crowdstrike/get_incident_summaries.yml
- registry/tracecat_registry/templates/crowdstrike/get_incidents.yml
- registry/tracecat_registry/templates/crowdstrike/list_incidents.yml
Adds templates for retrieving CrowdStrike CrowdScore Incidents and CrowdStrike CrowdScore Incident summaries. Also adds combined templates for retrieving detection/incident IDs and their summaries, all in one action.
1. Validate new action templates are valid
> feat(integration): Crowdstrike incidents + combined Get Detects/Incident templates

- registry/pyproject.toml
- registry/tracecat_registry/integrations/velociraptor.py
This integration runs a vql query against a Velociraptor server using a base64 encoded config as the secret. The configuration needs to be base64 encoded before adding it as a secret in Tracecat to preserve formatting.
You can use the following command to do so: `cat api.config.yaml | base64 -w` 
This action requires the following secrets for authentication:
* `velociraptor_ssl`
> feat(integration): Velociraptor integration

- frontend/src/components/executions/nav.tsx
- tracecat/workflow/executions/dependencies.py
- tracecat/workflow/executions/models.py
- tracecat/workflow/executions/router.py
- Fixes issue where scheduled workflow runs weren't properly loaded by the new executions loader. 
- Adds proper string parsing for schedule IDs (as these have colons)
- The colons are escaped in the api call, so we must unquote it at the router
https://github.com/user-attachments/assets/bbd653e2-b8e2-4914-87dc-1f0f70c3075d
> fix: Schedule run history issues

- registry/tracecat_registry/templates/crowdsec/search_ip_address.yml
- registry/tracecat_registry/templates/wazuh/update_agents.yml
Incorrect key name in `wazuh/update_agents.yml/upgrade_result`.
> fix(integration): Incorrect key name in crowdsec and wazuh

- docs/tutorials/2-control-flow.mdx
This PR corrects the documentation regarding Output Schema configuration in the Control Flow tutorial.
- Minor updates to configuration description
- Corrected 'List VirusTotal comments on URL' expression naming
Check section:
- docs/tutorials/2-control-flow.mdx
> docs(fix): Pathing mistake in control flow tutorial

- frontend/src/app/registry/actions/edit/page.tsx
- frontend/src/app/registry/actions/new/page.tsx
- frontend/src/components/editor/editor.tsx
- frontend/src/components/nav/workbench-nav.tsx
- frontend/src/components/workbench/panel/action-panel.tsx
- frontend/src/components/workbench/panel/workflow-panel.tsx
- We use module-level state to manage only registering completion/hover providers only once, when there are multiple editors on the same page
- Use yaml-extended as the defaultLanguage everywhere
> fix(ui): Prevent duplicate editor registrations + use yaml extended in all editors

- docker-compose.dev.yml
- docker-compose.yml
- Updated ollama service to use the same network as api service.
This PR fixes a bug where the api service could not connect to the ollama service, causing workflows using the ai_action step with the llama3.2:1b model to fail. The issue was due to the ollama service not being part of the same network as the api service. By aligning the network configuration in the docker-compose file, requests from the api service to the ollama service will now succeed.
Sample workflow
Error logs
1. Follow the deploy tutorial, using the latest docker-compose.yaml file
2. Run a workflow with an ai_action step using the llama3.2:1b model. You can recreate the workflow shown in the above image.
3. Confirm that the workflow completes successfully and the ai_action step does not fail.
> fix(infra): Align network configuration for api and ollama in docker-compose

- .env.example
- .github/workflows/test-python.yml
- Caddyfile
- docker-compose.dev.yml
- docker-compose.yml
- frontend/src/client/schemas.gen.ts
- frontend/src/client/services.gen.ts
- frontend/src/client/types.gen.ts
- frontend/src/components/executions/event-details.tsx
- tests/conftest.py
- tests/unit/test_workflows.py
- tracecat/api/app.py
- tracecat/api/executor.py
- tracecat/config.py
- tracecat/identifiers/__init__.py
- tracecat/registry/actions/router.py
- tracecat/registry/actions/service.py
- tracecat/registry/client.py
- tracecat/registry/constants.py
- tracecat/registry/executor.py
- tracecat/workflow/executions/service.py
- Move registry management endpoints (`/registry/repos` + `/registry/actions`) into `api` service
- Rename `registry` service to `executor` service. 
- Move and restructure old execution endpoints into `executor` module. Make service later.
- Add executor sync endpoint + Update registry sync to hit this
> refactor(engine): Move registry management endpoints into api service + restructure registry as executor service

- registry/tracecat_registry/integrations/ldap3.py
- registry/tracecat_registry/templates/ldap/disable_active_directory_user.yml
- registry/tracecat_registry/templates/ldap/enable_active_directory_user.yml
- registry/tracecat_registry/templates/ldap/expire_active_directory_user.yml
- registry/tracecat_registry/templates/ldap/expire_user.yml
- registry/tracecat_registry/templates/ldap/find_active_directory_users.yml
- registry/tracecat_registry/templates/ldap/find_users.yml
- tracecat/expressions/functions.py
- Converted existing LDAP UDFs into reusable templates to improve code maintainability and consistency.
- Added `add` and `delete` operations to LDAP client
- Introduced templates for enabling and disabling Active Directory users.
- Added templates for setting account expiration.
- Incorporated server and connection keyword arguments into LDAP templates for improved flexibility.
- Added function for handling Windows filetime conversions.
- Made the find users filters more precise
> feat(integration)!: Rewrite LDAP UDFs into templates

- tracecat/workflow/executions/models.py
- Fix types in wf runs history
> fix(engine): Use wf execution or schedule id for related wf exec ids

- registry/tracecat_registry/templates/ansible/run_playbook_from_s3.yml
- Use `integrations.ansible.run_ansible_playbook` (correct, from UDF) over `integrations.ansible.run_playbook`
> fix(integrations): Use correct function name for ansible run playbook

- tests/unit/test_executor.py
- tracecat/registry/executor.py
- Attempts to fix `RuntimeError: Task attached to different loop` error in `executor` service
- Use an initializer to create the `uvloop` event loop in each process pool worker instead of using `uvloop.run()` in the entrypoint function
- ~Added tests to verify that tasks are waited on the correct loop~
- The above tests were flaky, so rewrote most of them (or removed loop ID uniqueness checks)
> feat(engine): Improve process pool event loop management

- tracecat/registry/executor.py
- Wasn't merging the secrets context correctly
- Tested this with a unit test locally, works. Having issues with pytest fixtures here so just adding the patch first
The test i used:
```python
@pytest.mark.anyio
async def test_executor_can_run_udf_with_secrets(
mock_package, test_role, db_session_with_repo, mock_run_context
):
"""Test that the executor can run a UDF with secrets.
A UDF should be able to pull secrets directly from the secrets store.
"""
session, db_repo_id = db_session_with_repo
repo = Repository()
repo._register_udfs_from_package(mock_package)
assert repo.get("testing.fetch_secret").fn("KEY") is None  # type: ignore
sec_service = SecretsService(session, role=test_role)
await sec_service.create_secret(
SecretCreate(
name="test",
environment="default", …
```
> fix(engine): Load udf secrets in env correctly

- deployments/aws/ecs/ecs-temporal-ui.tf
- deployments/aws/ecs/variables.tf
- deployments/aws/main.tf
- deployments/aws/variables.tf
- Added variable `disable_temporal_ui` to disable / enable temporal UI service (`false` by default)
- Added missing Temporal UI variables in root terraform module
> ci(infra): Add temporal ui variables

- tracecat/workflow/schedules/bridge.py
- Fixes issue where workflows that take longer than the scheduled interval aren't ran in parallel, and are cancelled.
- NOTE: Users will have to recreate their schedules for the update to take place
Deployed and QAd on local + staging
> fix(engine): Use ALLOW_ALL schedule overlap policy

- tracecat/dsl/common.py
Fixes issue where `<ref>.error` paths weren't being parsed properly on workflow import
> fix(engine): Consider edge components when building graph

- deployments/aws/ecs/ecs-temporal-ui.tf
- deployments/aws/ecs/ecs-temporal.tf
- deployments/aws/ecs/locals.tf
- deployments/aws/ecs/variables.tf
- deployments/aws/main.tf
- deployments/aws/variables.tf
- tracecat/config.py
- tracecat/dsl/client.py
- Now supports both API key or MTLS client certs for authenticating a temporal client to temporal cloud server
- Added relevant terraform variables and made temporal server optional (but on by default) for Fargate
> feat(engine): Support Temporal API key and MTLS from AWS SM

- registry/tracecat_registry/base/core/workflow.py
- tests/unit/test_workflows.py
- tracecat/dsl/common.py
- tracecat/dsl/workflow.py
- tracecat/validation/service.py
- tracecat/workflow/executions/models.py
- tracecat/workflow/management/management.py
- Allow workflows to reference a child workflow by an alias
- Aliases are resolved into their corresponding workflow IDs
- Turn `ExecuteChildWorkflowArgs` into a pydantic `BaseModel`. 
- Add custom validator that checks that either workflow ID or alias is defined, now that workflow ID is marked optional in the UDF interface.
- Simplify how batch iteration works - consollidate all 3 strategies to use `itertoold.batched()` with different sizes.
- On `core.workflow.execute` udf schema
- Since this is a special action that doesn't run user logic, but rather platform logic, it's ok to have platform-level validation logic. 
- We no longer use validation from the `RegistryAction` table to validate this action but use the new pydantic BaseModel directly, since it has the custom validator (and …
> feat(engine): Implement runtime workflow alias resolution for child workflows

- frontend/src/components/nav/workbench-nav.tsx
Show the current workflow alias in the navbar (and nothing if there's none) without having to view the workflow panel.
See `workflows.root` in navbar breadcrumbs
> feat(ui): Add workflow alias to workbench navbar

- tests/unit/test_executor.py
- tests/unit/test_workflows.py
- tracecat/executor/router.py
- tracecat/executor/service.py
- tracecat/types/exceptions.py
- Structure errors as `RegistryActionErrorInfo` and return them when returning from the ray executor
- Reraise these as `WrappedExecutionError` and handle appropriately at the route level
Before
After
> fix(engine): Propagate executor error messages safely

- tests/conftest.py
Implement db fixture according to https://docs.sqlalchemy.org/en/20/orm/session_transaction.html#joining-a-session-into-an-external-transaction-such-as-for-test-suites. 
Use savepoint and serializable isolation level to enable rollback of nested transactions for function scoped tests
> test: Improve database fixture isolation

- registry/tracecat_registry/templates/okta/expire_sessions.yml
- registry/tracecat_registry/templates/okta/get_user.yml
- registry/tracecat_registry/templates/okta/get_user_by_email.yml
- registry/tracecat_registry/templates/okta/list_user_events.yml
- registry/tracecat_registry/templates/okta/reset_password.yml
- registry/tracecat_registry/templates/okta/suspend_user.yml
- registry/tracecat_registry/templates/okta/unsuspend_user.yml
- Replaced BASE_DOMAIN secret with BASE_URL arg
- Added doc_url to templates
- urlencoded email fields in path params
- Must provide url (with https://) vs domain
- URL is provided via inputs not secrets
> feat(integration)!: Normalize Okta templates  

- frontend/src/client/schemas.gen.ts
- frontend/src/client/types.gen.ts
- tests/unit/test_workflows.py
- tracecat/dsl/common.py
- tracecat/dsl/models.py
- tracecat/dsl/scheduler.py
- tracecat/dsl/workflow.py
- tracecat/workflow/executions/models.py
- tracecat/workflow/executions/service.py
- tracecat/workflow/management/management.py
- tracecat/workflow/management/models.py
Progresses #505
- Make workflows return some _sensible error info_. Current impl is a dict of action ref to `ActionErrorInfo`. This improves the final workflow execution event, and the error info shown to callers of child workflows.
- Add error handling functionality to `DSLWorkflow`. 
- A `Workflow` object may specify a workflow ID or alias as an error handler
- This must be a workflow that exists
- This workflow gets run if an error occurs in the primary workflow, and receives error info
- We wrap the existing workflow run logic with exception handling that triggers a child workflow that is the error handler.
- This needs to be embedded inside `DSLWorkflow` because of scheduled and pull-based workflows, where the DSL is not known until it's pulled from the DB after the workflow starts. …
> feat(engine): Implement error handler workflow functionality in DSLWorkflow

- frontend/src/components/nav/workbench-nav.tsx
- frontend/src/providers/workflow.tsx
- tracecat/workflow/management/management.py
- Cosmetic changes
- Renamed "commit" to "save" in the UI and error messages (components, endpoints, and variables are unchanged)
- Renamed tooltip for "Enable workflow" to be less technical
> feat(ui): Rename commit to save

- frontend/src/components/workbench/panel/action-panel.tsx
- frontend/src/components/workbench/panel/workflow-panel.tsx
- frontend/src/components/workbench/workbench.tsx
- frontend/src/lib/hooks.tsx
- Fixed state issues with error saving state and tabs selected persisting between nodes
- Fixed tab switcher content overflowing and the content (e.g. editor) remains the same size
- I deleted the toast when an action has malformed YAML. The state is really janky and removes immersion i.e. too aggressive (gives me unnecessary cortisol).
- ^I think this is feature of the past when we didn't have the really nice SaveStateIcon
> feat(ui): Add template tab and fix state actions on node click

- frontend/src/app/registry/actions/edit/page.tsx
- frontend/src/app/registry/actions/new/page.tsx
- frontend/src/client/schemas.gen.ts
- frontend/src/client/types.gen.ts
- frontend/src/components/auth/sign-up.tsx
- frontend/src/components/dashboard/workflow-tags-sidebar.tsx
- frontend/src/components/workbench/panel/action-panel.tsx
- frontend/src/components/workbench/panel/workflow-panel.tsx
- frontend/src/lib/errors.ts
- tracecat/api/app.py
- tracecat/registry/actions/models.py
- tracecat/registry/repositories/models.py
- tracecat/secrets/models.py
- tracecat/tags/models.py
- tracecat/workflow/actions/models.py
- tracecat/workflow/management/models.py
- tracecat/workflow/management/router.py
- tracecat/workspaces/models.py
- Make 422 unprocessible entity errors return an object with detail field: `{"detail": ...}`
- Tighten up input validation across FE zod schemas and API layer pydantic models
- Replace certain `Controller` fields with shadcn `FormField`
> feat: Tighten input validation

- tests/unit/test_organization_settings.py
- tracecat/api/executor.py
- tracecat/auth/dependencies.py
- tracecat/auth/users.py
- tracecat/registry/common.py
- tracecat/registry/repository.py
- tracecat/settings/service.py
- Add fallback to org settings `get_setting` as when users first move upgrade, they'll have empty configs in the db. We will fallback to the existing config variables to aid with the migration.
> fix(app): Add fallback for org settings

- frontend/next-env.d.ts
- frontend/src/components/executions/event-details.tsx
- tracecat/executor/models.py
- tracecat/workflow/executions/models.py
- Drop stack trace in failure handler
- Only show filename, function, and lineno in ExecutorActionErrorInfo if app env is "development"
- Also I think it's cleaner too from a UX perspective
> security: Drop stack trace from failure message

- frontend/src/components/executions/event-history.tsx
- frontend/src/lib/hooks.tsx
- tracecat/workflow/executions/service.py
- Add 2s refetch to the events column (this was present in the runs column) so you don't have to spam refresh
> feat(ui): Add refetchInterval of 2s to useWorkflowExecutionEventHistory

- frontend/next-env.d.ts
- frontend/src/client/schemas.gen.ts
- frontend/src/client/services.gen.ts
- frontend/src/client/types.gen.ts
- frontend/src/lib/hooks.tsx
- tests/unit/test_executor.py
- tests/unit/test_secrets_service.py
- tracecat/api/app.py
- tracecat/secrets/enums.py
- tracecat/secrets/models.py
- tracecat/secrets/router.py
- tracecat/secrets/service.py
- tracecat/validation/service.py
Separate out org secrets service methods and routers from workspace secrets. Note that they are currently stored in separate tables.
It's better security wise to keep these separate and prevents careless mistakes.
- Remove overloads from secrets service methods
- Remove `SecretLevel`
- Separate org secrets methods in secrets service
- Separate org secrets routers
- Use separate `RoleACL` for ws/org secret routers
Regular secrets usage works
Push/pull repos works
> refactor(app): Separate org secrets

- frontend/src/client/services.gen.ts
- frontend/src/client/types.gen.ts
- frontend/src/components/registry/registry-repos-table.tsx
- frontend/src/lib/hooks.tsx
- pyproject.toml
- tests/unit/test_executor_service.py
- tracecat/api/executor.py
- tracecat/dsl/action.py
- tracecat/dsl/models.py
- tracecat/executor/client.py
- tracecat/executor/models.py
- tracecat/executor/router.py
- tracecat/executor/service.py
- tracecat/git.py
- tracecat/registry/repositories/router.py
- tracecat/registry/repository.py
- tracecat/secrets/service.py
- tracecat/settings/service.py
- tracecat/ssh.py
- Use Ray's RuntimeEnv to manage custom udf repository, instead of having to push to executor to sync updates.
- Instead, when a user syncs the repo, we still pull the repo and update the action interfaces for the builder and registry, but we don't allow pushing to executor.
- We update the executor so that it checks the db repo for a SHA.
- For stability, we enforce that we pass a SHA with the git url into the ray RuntimeEnv. If no SHA is available, we don't install the remote repo as a dep.
- Ray caches the dependencies depending on the hash of the RuntimeEnv. If a change is observed, it will automatically `pip install` the updated version. For this reason, we always pass a SHA into the git url.
- Remove sync executors and validation from executor
> feat(engine): Basic implementation for pull-based executor and remove internal executor endpoints

- .github/workflows/test-python.yml
- Removed Temporal cli from python tests
- Remove `--no-deps`
> ci: Remove Temporal cli from Python tests

- registry/tracecat_registry/integrations/google_api.py
Resolve the following error due to passing json string directly into the call, when it expects a `Mapping` 
```
There was an error in the executor when calling action 'integrations.google_api.get_auth_token' (500).
AttributeError: 'str' object has no attribute 'keys'
------------------------------
File: /usr/local/lib/python3.12/site-packages/google/auth/_service_account_info.py
Function: from_dict
```
> fix(integrations): Ensure GOOGLE_API_CREDENTIALS is a mapping object

- tests/unit/test_executor_service.py
- tracecat/executor/service.py
- tracecat/registry/repository.py
- tracecat/ssh.py
Instead of delegating to Ray, manually manage the lifecycle of the ssh agent
> fix(engine): Manually manage ssh agent

- frontend/src/components/organization/org-ssh-key-create.tsx
- tests/unit/test_executor_service.py
- tests/unit/test_secrets_service.py
- tracecat/executor/service.py
- tracecat/registry/repository.py
- tracecat/secrets/models.py
- tracecat/secrets/service.py
- tracecat/ssh.py
Resolves the error below.
- Manual SSH agent management introduced much overhead, so we reverted that change
- Add zod validation in FE for ssh key
- When we pull the ssh key, add trailing newline character if its missing
- We learned that the Permissions Error in libcrypto is caused by a missing trailing newline in the SSH key. 
- The reason why only action execution was failing and not repo sync was because when we sync repos we are using manual ssh agent management. This involved creating SSH key tempfiles, which formats the ssh key properly. 
- With Ray's RuntimeEnv, this formatting does not seem to occur. 
- This error would only occur when the Ray head node detects a change in the dependency and decides it needs to pull deps. This meant that if no new commits were made to the remote …
> fix(engine): Revert Ray SSH agent changes and fix SSH key formatting

- registry/tracecat_registry/base/core/http.py
I also get confused sometimes between `params`, `payload`, and `form_data` and their associated methods. I don't think changing `payload` to `body` is a good idea, since technically `form_data` is also inside the request body. Anyway i think these descriptions clarify things. Does for me.
Prior art: I looked at curl / httpx's official descriptions of `data` / `json` arguments.
> docs(integrations): Clearer descriptions for `payload` and `form_data`

- tests/unit/test_functions.py
- tracecat/expressions/functions.py
We JSON serialize all inputs post-Pydantic validation before sending it over to the executor. This means datetimes are passed into each step in an action template as a JSON supported dtype (string, integer, float, object) only. There are no native JSON datetime objects.
- All datetime functions e.g. `format_datetime` run `to_datetime` (which converts an ISO 8601 datetime string into a datetime object) if the input is a string.
- Added more tests to check that important datetime functions e.g. `to_datetime` and `format_datetime` correct support both datetime and ISO string with and without timezone data.
- Added `parse_datetime` function, which supports python `strftime` formatting
- Dropped `to_timestamp_str` (the functionality and naming is strange, likely a hallucination, and I don't …
> feat(integrations): Support datetime or string in datetime functions

- deployments/aws/ecs/variables.tf
- deployments/aws/variables.tf
- docker-compose.yml
- docs/self-hosting/deployment-options/docker-compose.mdx
- docs/tutorials/updating.mdx
- tracecat/__init__.py
#785 needs to be in a separate PR from the workflow DB migration changes. This is so that if we rollback from 0.21.8+ (which contains ID changes in DB), the app won't just entirely break down. We may not be able to read workflow runs created in 0.21.8+, but at least you'll sitll be able to read existing workflow runs and operate on 0.21.8.
> release: 0.21.8

- registry/tracecat_registry/_internal/models.py
- tests/unit/test_templates.py
- tracecat/executor/service.py
- tracecat/registry/actions/models.py
- tracecat/registry/actions/service.py
- tracecat/registry/loaders.py
- tracecat/types/exceptions.py
We are changing executor so that it can be backend agnostic. We will be lifting up the secret retrieval logic into the `run_action_activity` on the Temporal worker -- all secrets must be pulled there and then injected into the action.
- **Make RegistrySecret hashable**
- Need this for set operations
- **Validate template action definition for self references to prevent infinite recursion**
- **Reduce loader boilerplate**
- **Add RegistryActionsService get_bound, fetch_all_action_secrets,  get_actions**
- **Lift up pulling secrets from outside of template action control flow**
- **Add integraiton test to verify nested secrets can be pulled**
- **Use TracecatValidationError over ValueError**
- This makes the transition to the new architecture easier. Also, we only make a single round trip …
> feat(engine): Pull all dependent secrets outside template action loop

- frontend/src/components/workbench/canvas/selector-node.tsx
This PR fixes an issue where the command menu's scroll position would jump unexpectedly when deleting characters in the search input. The scroll position should remain at the top regardless of whether the user is typing new characters or deleting them.
When deleting characters in the search input, more items become visible in the filtered list. The browser tries to maintain the relative scroll position of currently visible elements, causing an undesirable jumping effect.
We now force the scroll position to stay at the top after any input value changes by:
1. Updating the input value
2. Using `requestAnimationFrame` to wait for DOM updates
3. Explicitly setting the scroll position to 0 on the command list element
- Using `requestAnimationFrame` ensures our scroll reset happens after …
> fix(ui): Scrolling making workflow builder minify

- frontend/Dockerfile.prod
https://github.com/stackblitz-labs/bolt.diy/issues/1250
https://github.com/worldcoin/developer-portal/pull/1165
https://github.com/nodejs/corepack/pull/614
CI breaking due to corepack signature verification error. Pin corepack to a working version
> fix(ci): Pin working corepack version 

- tracecat/dsl/scheduler.py
We don't just brainlessly tick and poll - instead we wait for tasks to complete to awake the scheduling coroutine.
Cut tests duration by ~1.5min
> perf(engine): Improved DAG scheduling algorithm

- frontend/src/client/schemas.gen.ts
- frontend/src/client/types.gen.ts
- frontend/src/components/workbench/panel/action-panel-tooltips.tsx
- frontend/src/components/workbench/panel/action-panel.tsx
- pyproject.toml
- tests/unit/test_workflow_timers.py
- tracecat/api/app.py
- tracecat/api/common.py
- tracecat/dsl/action.py
- tracecat/dsl/common.py
- tracecat/dsl/models.py
- tracecat/dsl/workflow.py
- tracecat/expressions/validation.py
- tracecat/workflow/actions/models.py
- tracecat/workflow/executions/common.py
- tracecat/workflow/executions/models.py
- tracecat/workflow/executions/service.py
- tracecat/workflow/management/management.py
- Add `wait_until` - a `dateparser` compatible string that describes a datetime/relative timedelta for the action to wait before it executes
- Add `retry_until` - an optional expression field that returns a conditional, which will continue to rerun this action until this condition is met
> feat(engine): Add `wait_until` and `retry_until`

- tests/unit/test_expressions.py
- tracecat/expressions/functions.py
Changes the behavior of a jsonpath wildcard matching a single value only - it's more intuitive to return a list of single item
> fix(engine): Always return list when using jsonpath wildcard

- tests/data/test_actions/test_executor_functions.py
- tests/unit/test_executor.py
- tests/unit/test_parse.py
- tests/unit/test_workflows.py
- tracecat/dsl/action.py
- tracecat/executor/client.py
- tracecat/executor/models.py
- tracecat/executor/router.py
- tracecat/executor/service.py
- tracecat/expressions/validation.py
- tracecat/parse.py
- tracecat/registry/actions/models.py
- tracecat/types/exceptions.py
We weren't handling `WrappedExecutionError` properly in loop iteration, which led to uninformative errors like `Error in loop:` with no information. Now we capture more information and show it nicely.
- Added executor tests to reproduce the error, and ensure that we catch the improved exception with better diagnostics
Example of a loop iteration passing [1,2, None] into a UDF that expects an integer.
https://github.com/user-attachments/assets/c4c56937-a5cd-403f-9435-a0430f988caa
> fix(engine): Improve action loop error display

- registry/pyproject.toml
- registry/tracecat_registry/__main__.py
- registry/tracecat_registry/cli/entrypoint.py
- registry/tracecat_registry/cli/validate.py
- tracecat/registry/actions/service.py
- tracecat/registry/repository.py
- `--mode`: Validation mode
- `default`: Validate actions against actions in `tracecat_registry`. Doesn't need a live Tracecat stack. This is the default.
- `isolated`: Validate templates only. Doesn't need a live Tracecat stack.
- `db`: Validate templates and actions against a live Tracecat stack. 
- Pass `--db-uri` to specify the DB. Only relevant if `mode=db`. Otherwise, the CLI tries to read from `TRACECAT__DB_URI`, and falls back to `postgresql+psycopg://postgres:postgres@localhost:5432/postgres`
> feat(registry): Add CLI for template validation

- registry/tracecat_registry/templates/detect/lookup_domain/threatstream.yml
- registry/tracecat_registry/templates/detect/lookup_email/threatstream.yml
- registry/tracecat_registry/templates/detect/lookup_file_hash/threatstream.yml
- registry/tracecat_registry/templates/detect/lookup_ip_address/threatstream.yml
- registry/tracecat_registry/templates/detect/lookup_url/threatstream.yml
Merged #847 too eagerly.
- Added `ANOMALI` prefix to secret keys
- Fixed steps ref `make_request` (old) -> `get_reputation` (new) which was not updated after naming change
- We've merged a CLI for action template validation here: https://github.com/TracecatHQ/tracecat/pull/856
- Will create `CONTRIBUTIONS.md` by today 16th Feb to describe steps to validating templates locally
- Add validation with CLI to CICD in `test_registry` so action template tests fail quicker
> fix(integrations): Steps and API naming in anomali lookups

- registry/tracecat_registry/base/core/transform.py
- tests/registry/test_core_transform.py
- What used to be called `apply` is now `map`
- The current `core.transform.apply` function functions like a map (i.e. applies a function to a list of items one by one).
- This is inaccurate
- We need both `apply` (javascript style apply value to function) and `map` (python map wrapper)
- Added `apply` and `map` core transforms
- Added unit tests
> feat(core)!: Add `apply` and `map`

- frontend/src/client/schemas.gen.ts
- frontend/src/client/types.gen.ts
- frontend/src/components/workbench/events/events-selected-action.tsx
- tracecat/dsl/common.py
- tracecat/dsl/workflow.py
- tracecat/workflow/executions/models.py
- tracecat/workflow/executions/service.py
- Group up looped child workflow runs
- Add `child_wf_count` to track number of instances
- Add `loop_index`. Track this in `ChildWorkflowMemo` (need to distinguish between single loop iteration vs direct invocation)
> feat(ui): Merge child workflow compact runs

- frontend/src/lib/hooks.tsx
- tracecat/workflow/executions/service.py
Not the most glamorous approach but bumped the `onSuccess` delay to 200ms (from 50ms). Seems to handle the race condition ok. We'll see. Now we also just refetch once.
> fix(app): Try fix first builder run not showing up (again)

- frontend/src/components/workbench/canvas/action-node.tsx
- frontend/src/components/workbench/events/events-selected-action.tsx
- frontend/src/components/workbench/events/events-sidebar.tsx
- frontend/src/components/workbench/events/events-workflow.tsx
- frontend/src/lib/workflow.ts
- frontend/src/providers/builder.tsx
- Clicking on row in sidebar events no longer focuses node, only selects it
- Add ellipsis dropdown menu for left sidebar events with focus on node option
- Add selectors to inputs/results tabs for easy cycling between events
- Upgraded action node dropdown actions with `View Last Input` and `View Last Result`
https://github.com/user-attachments/assets/c3b2aa1f-3c9a-43dd-b267-24230ec07d32
https://github.com/user-attachments/assets/fb35da3e-5814-4a2f-94e6-67332cad0230
> feat(ui): Decouple left sidebar from action panel config

- frontend/src/components/workbench/canvas/action-node.tsx
- frontend/src/components/workbench/events/events-selected-action.tsx
- frontend/src/components/workbench/events/events-workflow.tsx
- frontend/src/lib/workflow.ts
- frontend/src/providers/builder.tsx
We had previously coupled the events sidebar with actions on the page. This meant that when an action was deleted from the canvas, you couldn't view the event in the sidebar. This PR fixes this behavior. We also disable focusing the canvas on the action if we can't find a matching action ref in the workflow.
> fix(ui): Further decouple events sidebar from canvas action

- docs/quickstart/tutorial.mdx
- frontend/src/components/workbench/panel/action-panel-tooltips.tsx
- Added more examples to frontend UI tooltip on if conditions
- A bit of formatting for the tooltip example inputs
- Added examples for each binary operator in if-conditions
- Added examples for `&&` and `||`
> docs: Add if-condition examples

- tests/unit/test_parse.py
- tracecat/auth/sandbox.py
- tracecat/dsl/workflow.py
- tracecat/executor/client.py
- tracecat/executor/models.py
- tracecat/executor/router.py
- tracecat/executor/service.py
- tracecat/parse.py
Reproduced the error with this setup:
1. Run a local http server that returns 1000 large nested jsons
2. Workflow hits this with `core.http_request` successfully
3. `for_each` over the data, trying to `FN.deserialize_json()`. This causes every single loop iteration to error out because the data is already json.
4. Observe recursion error
When handling executor errors, we were formatting error messages using `to_flat_dict`. This made us hit recursion limits quickly as it processes the entire result (if we looped N times, would return a list of N items). Decided to just show 1 instance of the error.
After removing `to_flat_dict`, we would observe the Temporal just gives up trying to return the error message because it exceeds the size limit. Fair enough. So we just return 1/N items since …
> fix(engine): Address loop recursion error issues

- frontend/src/components/icons.tsx
- frontend/src/components/workbench/panel/action-panel-tooltips.tsx
- registry/tracecat_registry/base/core/table.py
- registry/tracecat_registry/base/core/transform.py
- tests/conftest.py
- tests/unit/test_workflows.py
- tracecat/dsl/action.py
- tracecat/dsl/common.py
- tracecat/dsl/constants.py
- tracecat/dsl/enums.py
- tracecat/dsl/workflow.py
- tracecat/tables/router.py
- tracecat/tables/service.py
- tracecat/validation/service.py
- tracecat/workflow/executions/models.py
- Implement table lookup from workflows. We expose a `core.table.lookup` interface that's handled by native `DSLWorkflow` logic, as opposed to a udf implementation. See `core.workflow.execute` for reference.
- Update action node icon
- Added integration tests for calling in workflows
> feat(engine): Implement `core.table.lookup` action

- frontend/src/app/workspaces/[workspaceId]/tables/[tableId]/page.tsx
- frontend/src/app/workspaces/[workspaceId]/tables/layout.tsx
- frontend/src/app/workspaces/[workspaceId]/tables/page.tsx
- frontend/src/components/dashboard/create-workflow-button.tsx
- frontend/src/components/dashboard/workflow-tags-sidebar.tsx
- frontend/src/components/dashboard/workflows-dashboard.tsx
- frontend/src/components/nav/dynamic-nav.tsx
- frontend/src/components/nav/workspace-nav.tsx
- frontend/src/components/tables/table-create-dialog.tsx
- frontend/src/components/tables/table-delete-dialog.tsx
- frontend/src/components/tables/table-edit-dialog.tsx
- frontend/src/components/tables/table-insert-button.tsx
- frontend/src/components/tables/table-insert-column-dialog.tsx
- frontend/src/components/tables/table-insert-row-dialog.tsx
- frontend/src/components/tables/table-view-action-delete-dialog.tsx
- frontend/src/components/tables/table-view-action.tsx
- frontend/src/components/tables/table-view-column-menu.tsx
- frontend/src/components/tables/table-view.tsx
- frontend/src/components/tables/tables-dashboard.tsx
- frontend/src/components/tables/tables-side-nav.tsx
- frontend/src/lib/hooks.tsx
- frontend/src/lib/tables.ts
- Implement tables UI. We can now CRUD tables, columns, and rows from the UI.
- Remove "Find Playbook" button from workflows dashboard. Closes #886
- Added null check in `DynamicNav` if pathname is falsy. Hoping this addresses `Cannot read property 'useContext' of null` type of errors
> feat(ui): Add tables UI

- deployments/aws/ecs/variables.tf
- deployments/aws/variables.tf
In cloud, UI appears very sluggish because API service is only using 0.5vCPU and 1GB mem. Doubling this makes the UI appear more responsive as data loads faster.
This should also help avoiding timeouts during repo sync (likely caused by resource constraints)
> chore(infra): Increase defaults for api_cpu to 1024 and api_memory to 2048

- registry/tracecat_registry/schemas/notify/create_case.yml
- registry/tracecat_registry/templates/notify/create_case/jira.yml
- registry/tracecat_registry/templates/notify/post_todo/slack.yml
- registry/tracecat_registry/templates/tools/README.md
- registry/tracecat_registry/templates/tools/jira/get_fields.yml
- registry/tracecat_registry/templates/tools/jira/get_priorities.yml
- registry/tracecat_registry/templates/tools/jira/get_priority_schemes.yml
- registry/tracecat_registry/templates/tools/jira/get_projects.yml
- tests/registry/test_templates.py
- tests/unit/test_functions.py
- tests/unit/test_template_actions.py
- tracecat/expressions/functions.py
- Fixed `create_case` integration for Jira to support tags and metadata / custom fields.
- Changed `priority` to `priority_id`
- Added templates for get projects, get priorities by scheme, get priority schemes, get fields Jira endpoints (use-case: to populate lookup tables or map priority name to ID)
- Added `index_by_key` (turn list of dicts to dict) and `map_keys` inline functions
Replace paginated endpoints with `core.http_paginated` (enterprise only?)
> feat(integrations)!: Extend Jira create case with labels

- registry/tracecat_registry/templates/detect/lookup_url/urlscan.yml
With the introduction of #810 we can only easily implement async POST query then GET poll until result complete integrations. URLScan is one such canonical example.
> feat(integrations): Add URLScan template with polling

- registry/tracecat_registry/base/core/table.py
- tests/unit/test_workflows.py
- tracecat/dsl/action.py
- tracecat/dsl/common.py
- tracecat/tables/service.py
- tracecat/validation/service.py
- Tables weren't working with loops
- Fix incorrect type `str` for value field
- Remove special treatment for core.tables actions, treat as UDF. we just use TablesService directly from tracecat_registry
> fix(engine): Use UDF for table actions

- registry/tracecat_registry/base/core/require.py
- tests/registry/test_core_require.py
`conditions` is a more human-readable and meaningful name. Easier to understand when reading a template file.
> feat(core)! Rename exprs to conditions in `core.require` node

- frontend/src/components/workbench/panel/workflow-panel.tsx
- frontend/src/lib/errors.ts
- frontend/src/providers/workflow.tsx
- tracecat/db/common.py
- tracecat/workflow/management/router.py
- Start to build a system to catch and report specific violations of backend state (like db unique constraints). This design is a WIP, experimenting with mapping sqlalchemy `UniqueConstraints` to error messages.
> fix(ui): Add error handling for duplicate workflow alias

- docs/self-hosting/deployment-options/docker-compose.mdx
- env.sh
This PR rephrases second question in `env.sh` to make it more clear and adds warning when user tries to use `0.0.0.0` as address (see #887 )
Also updated installation docs for docker compose, reflecting changes in `env.sh` and adding note about IP addresses
Adds a variable check preventing user from encountering #887 
1. Clone repo - git clone https://github.com/TracecatHQ/tracecat.git
2. Run env.sh, leave first and third option default, but in second (where you are asked to specify server ip address) set it to 0.0.0.0
3. You will see an error message pointing to the documentation and script will ask you to enter IP again
4. Then if you enter valid address or domain, installation will continue as before
> chore: Updated `env.sh` prompt

- tests/unit/test_executor_service.py
- tests/unit/test_sandbox.py
- tracecat/auth/sandbox.py
- tracecat/executor/service.py
We weren't pulling optional secrets correctly in the executor. Include it in the secrets to fetch.
> fix(engine):: Optional secrets not handled correctly

- frontend/src/styles/globals.css
On staging, horizontal scrolling to the left navigates the browser back.
In localhost, trying to horizontal scroll to the left no longer navigates back.
https://github.com/user-attachments/assets/2b5462b0-0c56-45e9-bb47-5480fb3315ea
> fix(ui): Prevent trackpad overscroll on macos

- tests/unit/test_llms.py
Disable broken llm test and add more skip logic for local test runs.
See https://github.com/TracecatHQ/tracecat/actions/runs/13705543127. 
Logs:
```
==================================== ERRORS ====================================
________ ERROR at setup of TestTablesService.test_create_and_get_table _________
anyio_backend = 'asyncio'
request = <SubRequest 'svc_workspace' for <Function test_create_and_get_table>>
args = ()
kwargs = {'session': <sqlmodel.ext.asyncio.session.AsyncSession object at 0x7f9b44f696d0>}
local_func = <function svc_workspace at 0x7f9b4f3c5b20>
backend_name = 'asyncio', backend_options = {}
runner = <anyio._backends._asyncio.TestRunner object at 0x7f9b4413d6a0>
def wrapper(
*args: Any, anyio_backend: Any, request: SubRequest, **kwargs: Any
) -> Any:
if ( …
```
> test: Add more skip logic for local testing and disable failing llm tests

- frontend/src/components/organization/org-secret-update.tsx
- frontend/src/components/workspaces/edit-workspace-secret.tsx
- tests/unit/test_secrets_service.py
- tracecat/secrets/service.py
This PR enables the user to edit existing keys in both Workspace and Organization edit dialogs.
Fixes #872 
1. Add multiple a secret with keys
2. Click the three dots at the end
3. Click edit to open edit dialog
> feat(app): Allow editing of existing keys

- tests/unit/test_expressions.py
- tracecat/expressions/eval.py
Example: JSON Schema properties names are keys. I might want a template action where the name of the property is an argument.
This PR introduces support for dynamic dictionary keys using template expressions, along with corresponding validation logic. The changes include:
1. Enhanced the template object evaluation to support expressions in dictionary keys
2. Added comprehensive test coverage for dynamic key evaluation scenarios
3. Updated validation logic to properly handle expressions in dictionary keys
4. Fixed a minor inconsistency in validation result handling
- Modified `_eval_templated_obj_rec` to evaluate string dictionary keys using the provided operator
- Added test cases covering various scenarios for dynamic keys:
- Basic template key evaluation
- Multiple expressions within a …
> feat(engine): Support expressions in dictionary keys

- frontend/src/components/workbench/canvas/action-node.tsx
- frontend/src/components/workbench/events/events-sidebar.tsx
Some fun stuff.
- **Allow editing node title on the node**
- **Add more sidebarRef controls**
- **Replace node dropdown with floating toolbar menu**
- Move copy into toolbar
- Add 'Rename' to toolbar
- Running out of space for node options
- Finding options is more obvious
Overview
https://github.com/user-attachments/assets/28f9505b-47cd-4165-848d-a5e60be5e42d
You can still copy a previous node's ref while editing another
https://github.com/user-attachments/assets/92e4982c-0cd0-4504-ac41-70a3cb9d9ede
> feat(ui): Edit node title on node + floating node options

- tests/unit/test_parse.py
- tracecat/expressions/functions.py
- tracecat/parse.py
- Allows passing of `\n \t \r` etc (any number) into expressions as plain strings. The python functions see the escaped versions `\\n \\t \\r` etc, and replace them with the unescaped versions
- We currently only apply this onto `FN.join`
> feat(engine): Add unescape string for `FN.join()` separator

- frontend/src/components/workbench/canvas/action-node.tsx
- Make toolbar stay visible when moving back and forth between node <> toolbar.
- Also useMemo() for icon useCallback() to action node render method
> feat(ui): Toolbar stays visible when moving mouse back over node

- registry/tracecat_registry/templates/notify/post_notification/slack.yml
Remove text input from tools.slack.post_notification and make inputs.prompt a markdown section
> feat(integrations): Use markdown section for slack.post_notification prompt

- tracecat/identifiers/common.py
When we try to load workflow executions from spawning a list of child workflows, we were seeing this:
```
api                   | temporalio.client.WorkflowQueryFailedError: [TMPRL1100] Nondeterminism error: Child workflow id of scheduled event 'wf_4Va5Yb7xLsIXIXiLjdjNob/exec_2gH9iBkiKfKi7gBiotWVXm' does not match child workflow id of command 'wf_4Va5Yb7xLsIXIXiLjdjNob/exec_07gFQ2ICmvLwVxxrWMfdFH
```
during workflow replay. In particular, it happens when we try to `query` the workflow execution in the workflow executions service, after we added interactions.
From kapa.ai:
> 
> You're encountering a non-deterministic error when querying a workflow. This error occurs because there's a mismatch between the child workflow ID that was used during the original workflow execution and the ID …
> fix(engine): Use temporal's workflow.uuid4() if we're inside the workflow sandbox

- frontend/src/client/schemas.gen.ts
- frontend/src/client/types.gen.ts
- frontend/src/components/organization/org-settings-app.tsx
- frontend/src/components/workbench/events/events-sidebar.tsx
- frontend/src/components/workbench/panel/action-panel.tsx
- tracecat/settings/models.py
- tracecat/workflow/executions/router.py
The interactions can be toggled on/off from the UI. The reason is that it's incomplete -- needs to be backed by a DB, instead of relying on temporal query.
https://github.com/user-attachments/assets/fa011198-3160-4abd-b861-77cb9bb0e4bc
> feat(ui): Make interactions toggleable

- Caddyfile
- deployments/aws/ecs/ecs-caddy.tf
- deployments/aws/ecs/ecs-worker.tf
- deployments/aws/ecs/ecs.tf
- deployments/aws/ecs/security_groups.tf
- deployments/aws/ecs/variables.tf
- deployments/aws/main.tf
- deployments/aws/variables.tf
- tracecat/dsl/client.py
- tracecat/dsl/scheduler.py
- **Add prometheus to worker**
- **Bind to 0.0.0.0 and expose /metrics in caddy**
- **Catch exception for ActionErrorInfo**
- **ci: Add prom metrics to fargate (#981)**
- **Expose metrics port**
- **ci(fix): Cursor overwrote ui reverse proxy**
- **fix env vars injection in ecs-caddy**
- **Another try**
- **caddy depend on worker**
- **fix deprecated basic auth directive**
- **anoher attempt**
- **revert caddy changes**
- **deprecated directive**
- **Caddyfile again**
- **hardcode**
- **try again but with the working script**
- **test without basic auth**
- **Update security groups**
- **missing caddy security group in ecs worker**
- **Add basic auth**
- **Revert "Catch exception for ActionErrorInfo"**
- **Revert "Revert "Catch exception for ActionErrorInfo""**
- **Try parse errors …
> fix: Fix  deadlock issue when unexpected keyword in error info + add more metrics

- deployments/aws/ecs/locals.tf
- deployments/aws/ecs/variables.tf
- deployments/aws/main.tf
- deployments/aws/variables.tf
- docker-compose.dev.yml
- docker-compose.yml
- pyproject.toml
- tracecat/dsl/action.py
- tracecat/dsl/interceptor.py
- tracecat/dsl/scheduler.py
- tracecat/dsl/worker.py
- tracecat/dsl/workflow.py
- tracecat/executor/client.py
Add sentry interceptor based on https://github.com/temporalio/samples-python/tree/main/sentry. 
If SENTRY_DSN is defiend on a worker, we initialize the `sentry_sdk` and add a `SentryInterceptor` to the temporal worker.
Lowered log level to avoid using `logger.error`, as sentry automatically captures those as issues.
Note that we have issues using `sentry_sdk.capture_exception()`. Some kind of metaclass issue. It works on v1.45.1 of sentry-sdk in Temporal's sample. 
```
|            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
worker-1              |   File "/usr/local/lib/python3.12/site-packages/temporalio/worker/workflow_sandbox/_importer.py", line 234, in _import
worker-1              |     mod = importlib.__import__(name, globals, locals, fromlist, level)
worker-1              | …
```
> feat(engine): Add sentry

- tracecat/dsl/interceptor.py
Update sentry alert fingerprints to be `[<workflow ID>, <trigger type>]` so that alerts are grouped separately. See sentry for examples.
Also alert on webhook events.
> feat(engine): Update sentry fingerprinting, add more tags, alert on webhook events

- frontend/src/components/tables/table-view.tsx
When text values got too long, the table became a little too cluttered 
#975 
1. Create a table with a text column
2. Add a value with more then 25 characters
> feat(ui): Collapse text with 25 chars plus in lookup tables

- frontend/src/components/tables/table-import-csv-dialog.tsx
- frontend/src/components/tables/table-view.tsx
This PR fixes the UI malfunction that has long texts passing boundaries in the csv
Fixes #1012 
CSV:
1. Choose a CSV with large amounts of text
2. The next dialog window should collapse the text
Table View:
1. Add an arbitrary number of text columns to a table
2. Add rows with long text
> fix(ui): Fixing csv import window and handling large texts

- frontend/src/components/cases/case-comments-section.tsx
- frontend/src/components/cases/case-panel-custom-fields.tsx
- frontend/src/components/cases/case-panel-view.tsx
- frontend/src/components/cases/case-table.tsx
- frontend/src/components/cases/case-workflow-trigger.tsx
- frontend/src/components/sliding-panel.tsx
- frontend/src/providers/case-panel.tsx
Use query params to navigate to case panel. This makes it less disorienting when refreshing the page. Also makes it easier to share urls to casees.
https://github.com/user-attachments/assets/673e002e-e09a-4ed9-94c6-a775b01b7ddf
> feat(ui): Use query params for case panel

- tracecat/api/app.py
- tracecat/api/common.py
- tracecat/api/executor.py
Sometimes we need to destroy Temporal's volumes and thus destroy any custom search attributes.
Currently we've added search attributes in alembic migration. From the DB's POV it has already
applied the migration. To address this, we add search attributes in FastAPI lifespan in API ~and executor services~ (update: remove this in executor, executor doesn't know about the existence of Temporal). Ideally this should run in a shell script before any services start.
> feat(engine): Add Temporal search attributes in FastAPI lifespan for API

- frontend/src/components/workbench/canvas/canvas.tsx
- Removing the delete keypress in the react flow canvas makes it so you can't delete edges either.
> fix(ui): Add delete keypress back

- registry/tracecat_registry/templates/detect/query_events/splunk.yml
An Action Template that:
1. Posts search query with http request
2. Extract search ID with simple python apply
3. Polls search job endpoint until `dispatchState` is `DONE`
4. Gets results
> feat(integrations): Splunk search job and results

- tracecat/webhooks/dependencies.py
add .limit(1) when querying for the latest workflow definition
> perf(app): Return only 1 workflow definition in webhook fastapi dependency

- frontend/src/components/workbench/canvas/action-node.tsx
This is useful for when a user is working on a node that requires other action refs
https://github.com/user-attachments/assets/db575936-445a-4516-86b7-0bc1b2102bd6
> fix(ui): Fix action ref copy and don't select node when clicking on toolbar

- pyproject.toml
- registry/tracecat_registry/llm/anthropic_bedrock.py
- tracecat/llm/__init__.py
- tracecat/llm/anthropic_bedrock.py
I wanted to use Claude via Bedrock in a way similar to how tracecat supports Ollama/OpenAI, so I implemented that. It only supports role-based/environment variable based auth; I'm not sure if others would want to store keys as secrets (AWS doesn't recommend this). 
Sorry, couldn't get tests to run. Not sure if the registry directory structured changed or what, but I don't _think_ this will break any tests
```    from tracecat.registry.actions.models import (
tracecat/registry/actions/models.py:20: in <module>
from tracecat_registry import RegistrySecret
E   ModuleNotFoundError: No module named 'tracecat_registry'```
> Add Anthropic support via Bedrock

- frontend/src/components/ui/popover.tsx
- frontend/src/components/workbench/canvas/action-node.tsx
- frontend/src/components/workbench/panel/action-panel.tsx
- **Expand action panel on node select if collapsed**
- **Expand action panel when node clicked**
- **Add portal prop to popover**
- **Add types for tab names**
> feat(ui): Add action panel ref + expand action panel on node click

- tracecat/dsl/models.py
- tracecat/dsl/scheduler.py
When we handle the error path sometimes the `details` becomes `None`. We weren't handling this correctly which led to the TypeAdapter(ActionErrorInfo) failing to parse None values
> fix(engine): More extensive error path handling and avoid null ActionErrorInfo

- frontend/src/client/schemas.gen.ts
- frontend/src/client/types.gen.ts
- frontend/src/components/tables/table-view-column-menu.tsx
- frontend/src/components/tables/table-view.tsx
- frontend/src/lib/hooks.tsx
- tests/conftest.py
- tests/unit/test_tables_service.py
- tracecat/tables/models.py
- tracecat/tables/router.py
- tracecat/tables/service.py
- Only support single index now
- Use sqlalchemy inspect to get indexes
- Renamed "natural key" to "unique index"
- Changed key icon to database spark
- Added ValueError (reraised as HTTP 400 error at router) exception to table service if update column with `is_index=True` and an index already exists
- Catch 400 exception in frontend updateColumn use effect
Silent bug where multi index path was reachable by user.
- Create new table
- Create index
- Create another index (errors as notification)
> fix: Drop multiindex support

- frontend/src/app/page.tsx
When logging in with oauth/saml we flicker to the login page for a split second
https://github.com/user-attachments/assets/479878ac-e335-456b-8bcd-362e7fb93492
https://github.com/user-attachments/assets/a1a63f2b-916a-4eb8-9382-bb827bf295e5
> fix(ui): Handle oauth/saml login loading states gracefully

- tracecat/dsl/common.py
- tracecat/dsl/workflow.py
- tracecat/workflow/executions/models.py
We weren't passing memo into the child workflow, which led to unexpected API errors as the error workflow's action ref would be blank and break the UI.
> fix(engine): Pass memo into error workflow

- tracecat/settings/router.py
All user roles need to be able to read organization app settings to conditionally render UI (e.g. disable exports). This contains non-sensitive values so it's safe
> feat(app): Allow all org users to read app settings

- tests/unit/test_workflows.py
- tracecat/dsl/models.py
- tracecat/dsl/workflow.py
- tracecat/workflow/executions/models.py
- **Add passing child workflow memo into error workflow**
- **Add url to error workflow info**
- **Rename url**
- **Return a list of errors instead of dict**
Any workflow exceptions are caught gracefully in the DSLScheduler and handled [here](https://github.com/TracecatHQ/tracecat/blob/e8e1bd9ce58e151bc49dd1232104f5765469f731/tracecat/dsl/workflow.py#L404).  In this [part of the PR](https://github.com/TracecatHQ/tracecat/pull/1091/files#diff-2079223e69c50358b1cca8d442dc92a6a030ecf15a15c8d995c7406b221441f9R230-R244) we handle the unexpected case where this isn't a dictionary and return an error instead of crashing the workflow.
https://github.com/user-attachments/assets/0b35b433-238d-45ad-839e-2c090771fbae
> feat(engine): Add url to error workflow info and return errors as list

- frontend/src/client/schemas.gen.ts
- frontend/src/client/types.gen.ts
- frontend/src/components/workbench/events/events-workflow.tsx
- registry/tracecat_registry/core/workflow.py
- tests/unit/test_workflows.py
- tracecat/dsl/common.py
- tracecat/dsl/enums.py
- tracecat/dsl/workflow.py
- tracecat/workflow/executions/enums.py
- tracecat/workflow/executions/models.py
- tracecat/workflow/executions/service.py
- Add fire-and-forget style child workflow execution. 
- If the parent completes or fails, the child will remain unaffected. Its timeout can be independently set as well.
The first run is the original behavior of child workflows "wait" mode. I show the completions of the child workflows here.
The second run is "detached" mode. I show that there are no completions here.
https://github.com/user-attachments/assets/a9ffcb67-6157-455c-8963-80c58a521a98
Here, see that the workflows did complete -- just not observed by the parent.
https://github.com/user-attachments/assets/7cde851c-49df-435e-919f-7337b54d8833
> feat(engine): Implement detached child workflows

- frontend/src/components/cases/case-workflow-trigger.tsx
- Add ~checkbox~ toggle in case workflow trigger to allow passing case fields at the trigger input root.
- This is saved to localstorage
Allows direct invocation of workflows designed to receive arguments directly from the trigger root. i.e. `TRIGGER.<field>`
> feat(ui): Add toggle to group case fields in trigger input

- pyproject.toml
The below issue happens when trying to pip install both `tracecat` and `tracecat_registry` (or the custom integrations starter kit) into the same venv.
```
× No solution found when resolving script dependencies:
╰─▶ Because only tracecat==0.34.2 is available and tracecat==0.34.2 depends on fastapi==0.111.0, we can conclude that
all versions of tracecat depend on fastapi==0.111.0.
And because pycti==6.6.3 depends on fastapi>=0.115.8, we can conclude that pycti==6.6.3 and all versions of
tracecat are incompatible.
And because tracecat-registry==0.1.0 depends on pycti==6.6.3 and only tracecat-registry==0.1.0 is available, we
can conclude that all versions of tracecat and all versions of tracecat-registry are incompatible.
And because you require tracecat and tracecat-registry, we can …
```
> build(deps): Bump fastapi + uvicorn

- scripts/openapi_to_template.py
- scripts/openapi_to_template_example_config.yaml
Blocked by https://github.com/TracecatHQ/tracecat/pull/1111
- Script that takes OAS3.0 spec and converts it into Tracecat action templates. Requires tracecat and tracecat_registry to be installed.
- Not perfect but will do most of the conversion work
- You can configure the generation by passing `--config`. 
- See schema and example inputs in the Pydantic models
- An example config file is provided.
- Having a notion of an `undefined` or `Unset` type/sentinel would have made this much easier. We don't have a nice way to omit params in action template `args`
- Tested locally with successful sync of jira and sentinelone openapi specs. Performed successful query of jira users endpoint.
- Able to ingest ms graph openapi spec as well. Didn't test with the full spec but able to ingest a subset …
> feat(integrations): Add openapi to action template script

- tests/unit/test_workflows.py
Tests would intermittently fail because `test_workflow_detached_child_workflow` would return pending children out of order.
```
2025-05-09 16:14:36.343833Z [30981] | INFO      test_workflows:test_workflow_detached_child_workflow:3162 - pending_children | {'pending_children': [workflow_id: "wf_37s1zQPZlYqHqIYjsR7K2k/exec_1tjgU3Pk5pP7AVHeVYtcGl"
run_id: "0196b59c-d468-7c5e-9f8b-69ff62f93005"
workflow_type_name: "DSLWorkflow"
initiated_id: 34
parent_close_policy: PARENT_CLOSE_POLICY_ABANDON
, workflow_id: "wf_37s1zQPZlYqHqIYjsR7K2k/exec_2ub7gXEOr7G0Tqg2vIq7Y0"
run_id: "0196b59c-d479-7ab0-8135-5d28005e58bd"
workflow_type_name: "DSLWorkflow"
initiated_id: 32
parent_close_policy: PARENT_CLOSE_POLICY_ABANDON
, workflow_id: "wf_37s1zQPZlYqHqIYjsR7K2k/exec_6eGKhDN7ocFMeZ1ONc1e5y"
run_id: …
```
> fix(test): Sort pending children by initiated ID

- tracecat/workflow/actions/router.py
- Race condition
- Action in table gets deleted before the action in the workflow definition.
- When this happens, causes unrecoverable error. No longer able to SAVE the workflow (action not found) NOR delete the action (action not found).
Hard to reproduce. But this happened only when I started deleting a bunch of nodes in rapid succession.
- Do not raise "resource not found" error if action delete finds no action.
Not to my knowledge. It seems safe to ignore a delete if it doesn't exist.
Can delete node then save workflow.
> fix(engine): Ignore action delete if not found

- frontend/src/components/workbench/canvas/canvas.tsx
- frontend/src/lib/workflow.ts
- frontend/src/providers/builder.tsx
- frontend/tests/workflow.test.ts
Aim to eliminate ghost edges which makes UX awkward. Solving at the root cause would be much more challenging and involved than retroactively patching the graph object.
- **We don't actually use pendingDeleteEdges**
- **Drop ghost edges in graph prune step**
- **Simplify ephemeral node pruning logic**
- **pruneGraphObject -> pruneReactFlowInstance**
- **Defensive graph prune on layout + initialize**
- Update graph pruning logic to drop ghost edges
- Add tests for grpah pruning logic (TODO: Add to CI)
- Run pruning on canvas initialization and onLayout handler
- Simplify `isEphemeral` check in prune step
> fix(ui): Add defensive graph pruning on canvas init + layout

- registry/tracecat_registry/templates/tools/slack/chat/post_message.yml
- registry/tracecat_registry/templates/tools/slack/custom/post_notification.yml
- registry/tracecat_registry/templates/tools/slack/custom/post_update.yml
- tracecat/ee/interactions/connectors.py
- Rename `interaction_context` in slack metadata to just `context`
- Add interaction context back into other slack post message calls
> feat(engine+integrations): Add interaction metadata

- docker-compose.dev.yml
- docker-compose.yml
- tracecat/dsl/client.py
Should fix  #1127 
- Worker is the smallest image seems to spin up too early (before `temporal` and `api` is ready)
- We have retry connection for worker but it only retries up to 10 seconds
- Increase worker connection retry to 2 minutes
- Add `depends_on` in docker compose to worker (now waits for `temporal` and `api`)
> build(fix): More conservative retries and depends on

- frontend/src/client/schemas.gen.ts
- frontend/src/client/types.gen.ts
- frontend/src/components/builder/builder.tsx
- frontend/src/components/builder/events/events-sidebar-toolbar.tsx
- frontend/src/components/builder/events/events-sidebar.tsx
- frontend/src/components/builder/events/events-workflow.tsx
- frontend/src/components/executions/event-history.tsx
- frontend/src/lib/hooks.tsx
- tracecat/dsl/common.py
- tracecat/workflow/executions/common.py
- tracecat/workflow/executions/models.py
- tracecat/workflow/executions/router.py
- Add events sidebar toolbar
- Toolbar currently contains "filter", which will let you multi-select one or more trigger types.
- This toolbar can be extended to have other functionality
- **Allow querying for last execution with all trigger types**
- **Update openapi ts client**
- **WIP**
- **Add floating events toolbar**
> feat(app): Implement events toolbar

- registry/pyproject.toml
- registry/tracecat_registry/integrations/agents/builder.py
- registry/tracecat_registry/integrations/pydantic_ai.py
- tests/conftest.py
- tests/registry/mcp/test_slackbot.py
- tests/registry/test_pydantic_ai.py
- tests/unit/test_agent_builder.py
- tests/unit/test_auth_middleware.py
This PR introduces `TracecatAgentBuilder`, a builder class for creating Pydantic AI agents with Tracecat registry tools. Key changes:
- Implemented `create_tool_from_registry()` to dynamically convert registry actions into Pydantic AI tools
- Added support for namespace and action filtering to limit available tools
- Implemented automatic secret handling via `AuthSandbox` for secure tool execution
- Created `call_tracecat_action()` to handle runtime execution with proper secret management
- Added helper functions for docstring generation and function signature creation
- Exposed `agent()` registry function for direct API integration
- Unit tests for individual helper functions with mocked dependencies
- Integration tests with real registry actions including core HTTP and Python scripting …
> feat(agents): Tool calling agent-as-an-action

- tracecat/dsl/workflow.py
Prevents unnecessary duplication of history size
> perf(engine): Skip validate trigger inputs earlier

- frontend/src/app/workspaces/[workspaceId]/integrations/[providerId]/page.tsx
- frontend/src/app/workspaces/[workspaceId]/tables/[tableId]/page.tsx
- frontend/src/components/nav/builder-nav.tsx
<BreadcrumbLink> component isn't caching properly. Replacing with nextjs <Link> seems to help. 
https://github.com/user-attachments/assets/bcf8ec99-c1f3-4a41-82fa-24905ab1212c
https://github.com/user-attachments/assets/d2bc2234-45ca-444b-9098-6b2ba3a9c65a
> perf(ui): Cache workflows page using nextjs Link

- tracecat/workflow/schedules/bridge.py
- tracecat/workflow/schedules/service.py
Scheduled workflows run with `AccessLevel.BASIC`:
Use `AccessLevel.ADMIN` role for schedules
Currently, creating and deleting the row fails with the error shown in the screenshot
https://github.com/user-attachments/assets/55a9e6dd-96b9-4b8b-b13c-18fac09f5e1f
After adding these changes, recreating the schedule (important, as the role isn't dynamic) for the same workflow runs successfully.
https://github.com/user-attachments/assets/72745211-646e-4b3f-ac16-82a39e705c44
> feat(engine): Given schedules admin role
