services.sh
- Pass --tail to attached, run in detached mode if not passed
- Pass --build to rebuild internal services
=> feat: Pass build flags into services.sh

docs/core/actions.mdx, docs/core/integrations.mdx
- Add instructions and examples for integrations
- Small update for actions
=> docs: Update integrations docs

aws/stack.py, tracecat/api/app.py, tracecat/runner/app.py
These endpoints allow us to test connectivity between API and runners
=> feat: Add endpoint to ping API / runner from runner / API

frontend/src/components/cases/table.tsx, frontend/src/lib/cases.ts, frontend/src/providers/cases.tsx, tracecat/types/api.py
- Update pydantic schema for cases
- Create `commit` button for autocomplete
- Committing changes syncs the change in Tantivy using the API
=> feat(ui+engine): Add basic case autocomplete persistence

frontend/src/app/auth/callback/route.ts, frontend/src/lib/auth.ts
=> fix: Improve exception handling for auth callback new user flow

frontend/src/components/cases/table.tsx, frontend/src/providers/cases.tsx
- Move some of the state contained in the cases table into the cases provider (mutate)
- Use mutateAsync instead of regular mutate
- Add confirmation dialog
=> feat+refactor(ui): Add autocomplete commit confirmation + move some state into the provider

frontend/src/app/settings/credentials/page.tsx, frontend/src/components/cases/columns.tsx, frontend/src/components/cases/panel-content.tsx, frontend/src/components/console/control-panel.tsx, frontend/src/components/new-credential-dialog.tsx, frontend/src/components/shallow-kv-table.tsx, frontend/src/components/workspace/panel/action/form.tsx, frontend/src/components/workspace/panel/action/schemas.tsx, frontend/src/components/workspace/panel/common.tsx, frontend/src/providers/case-panel.tsx, frontend/src/styles/tailwind.ts, frontend/src/types/schemas.ts, frontend/src/types/validators.ts, tracecat/db.py, tracecat/runner/actions.py, tracecat/types/api.py, tracecat/types/cases.py
- Make UI styles consistent with rest of the app
- Add flat KV form field
- Add tags (KV)
- Change suppression to use KV
- Remove `tags` argument from runner `Action` and relevant function calls, clashes with `tags`
- Use `RootModel` to cleanly parse `list[Tag]` and `list[Suppression]`
=> feat(ui+engine): Improve case management [1/N]

pyproject.toml, tests/conftest.py, tests/data/log_samples/aws_cloudtrail/cloudtrail_insights.json, tests/data/log_samples/aws_cloudtrail/cloudtrail_update_trail_error.json, tests/data/log_samples/aws_cloudtrail/ec2_create_key_pair.json, tests/data/log_samples/aws_cloudtrail/ec2_start_instances.json, tests/data/log_samples/aws_cloudtrail/ec2_stop_instances.json, tests/data/log_samples/aws_cloudtrail/iam_add_user_to_group.json, tests/data/log_samples/aws_cloudtrail/iam_create_role.json, tests/data/log_samples/aws_cloudtrail/iam_create_user.json, tests/data/log_samples/aws_cloudtrail/kms_rotate_keys.json, tests/etl/test_aws_cloudtrail.py, tracecat/config.py, tracecat/etl/aws_cloudtrail.py, tracecat/etl/aws_s3.py
Closes #56 
Yes. I've added tests to check that the number of downloaded log samples equals the number of uploaded log samples. I've also tested that the downloaded logs samples equals the upload log samples exactly.
=> feat(engine): AWS CloudTrail gzipped json reader

frontend/src/components/cases/columns.tsx
- Fix unwanted behavior where clicking the checkbox on a table row triggers the side panel
=> fix(ui): Prevent checkbox from propagating click event

docs/installation.mdx
=> docs: Update installation to include supabase cli

tracecat/etl/query_builder.py, tracecat/integrations/aws_cloudtrail.py
=> feat: Add native AWS CloudTrail query integration

.env.example, tests/data/log_samples/emailrep/email.json, tests/integrations/test_emailrep.py, tracecat/integrations/emailrep.py
=> feat(integration): Emailrep check reputation

docs/installation.mdx
=> docs: Add linux docker networking fix

tracecat/db.py
=> fix(engine): Get Resource.updated_at working

docs/installation.mdx
=> docs: Spelling in installation

docs/installation.mdx
=> docs: Update installation section

tracecat/actions/__init__.py, tracecat/actions/core/transform.py
#Features
- Add `core.transform.forward` UDF
=> feat(engine): Add data transform forward action

tracecat/cli/workflow.py
- Add to `tracecat workflow run` `--proxy` switch to control whether webhooks are called directly (proxy=false) or through a proxy/ingress tunnel
=> feat(cli): Enable webhook trigger without ingress tunnel

tests/unit/integrations/test_extraction.py, tracecat/actions/integrations/extraction/__init__.py, tracecat/actions/integrations/extraction/email.py, tracecat/actions/integrations/extraction/ip_address.py
=> feat(integration): Add email and ipv4 extractors

pyproject.toml, tests/unit/integrations/test_sinks.py, tracecat/actions/integrations/sinks/__init__.py, tracecat/actions/integrations/sinks/database.py
- Added ADBC postgres, sqlite, and snowflake drivers to dependencies
- Added `write_to_database` function to support writing data to databases using ADBC drivers.
- Added unit test that checks write to sqlite database
=> feat(integration): Add database writer

docs/concepts/expressions.mdx, docs/concepts/secrets.mdx, docs/deployment.mdx, docs/installation.mdx
- Add funciton expressions table
=> docs: Update docs for single docker compose file

tracecat/dsl/common.py, tracecat/types/exceptions.py
- Bubble up Tracecat DSL exceptions when validation fails
- All unit tests passing
=> feat(engine): Use TracecatDSLError in DSL validation

frontend/src/components/icons.tsx, tracecat/actions/core/llm.py, tracecat/api/completions.py, tracecat/llm.py
- Reduce into single AI action, which just takes a prompt and optional system context
=> feat(udf): Update AI action

tests/data/workflows/integration_webhook_concat.yml, tests/integration/test_webhook.py, tests/unit/test_expressions.py, tracecat/expressions/engine.py, tracecat/expressions/patterns.py
- Added missing TRIGGER context expressions for parser
- Added more expression unit tests
- Added webhook integration test
=> feat(engine): Trigger context handling + webhook integration test

tests/data/workflows/integration_core_ai_action.yml, tracecat/actions/core/llm.py
- Added integration test for AI actoin
- Fix wrong parameter usage
- To run this in CI
- Manual QA testing, verified case opened from CLI
```sh
❯ tracecat workflow cases wf-ded8137b39b74d42a96b38898338640e
2024-06-24 16:06:12.630 | WARNING  | tracecat.auth.credentials:<module>:132 - User authentication is disabled, using default user.
[
{
'id': 'case-c4e25b7b25354c81bbadc61837001e70',
'owner_id': 'default-tracecat-user',
'workflow_id': 'wf-ded8137b39b74d42a96b38898338640e',
'case_title': 'Interesting Case',
'payload': {
'text': "Did you know that honey never spoils? Archaeologists have found pots of honey in ancient Egyptian tombs that are over 3,000 years old and still perfectly edible. 
Honey's unique chemical composition and low water content create an environment that's inhospitable …
```
=> fix+test: Add integration test for AI action

pyproject.toml, tracecat/actions/integrations/enrichment/shodan.py
- Added analyze URL function (aka hostname filter in shodan)
- Added analyze IP function
=> feat(integration): Shodan analyze URL / ip address

playbooks/alert_management/crowdstrike-to-cases.yml, playbooks/alert_management/slack-to-crowdstrike-update.yml, tests/data/log_samples/crowdstrike/alert.json, tracecat/api/app.py, tracecat/dsl/common.py, tracecat/expressions/functions.py, tracecat/parse.py, tracecat/types/api.py
- Add api logic to handle child workflows. Extensible to other kinds of callbacks
- Allow action tests to use list and dict
- Live QA with runtime mocking works
=> feat: CS-slack sync working

.github/workflows/test.yml, docker-compose.yml
- Remove Temporal Elasticsearch + its volume from the base compose stack
- Remove from CI as well
=> build: Remove elasticsearch

tests/unit/test_sandbox.py, tracecat/auth/sandbox.py, tracecat/concurrency.py
- Add `GatheringTaskGroup` as convenience wrapper around `asyuncio.TaskGroup`
- Raise Tracecat exceptions to signal missing secrets
- Updated test_sandbox unit tests
=> feat(engine): Improve missing secrets visibility in AuthSandbox 

tracecat/registry.py
- Explicitly define the `@registry.register` metadata options
- Remove `**register_kwargs` as there isn't a good use case + it's error prone
=> feat(engine): Make registry metadata a TypedDict

frontend/src/components/nav/workflow-nav.tsx, frontend/src/components/workspace/panel/workflow/controls.tsx, frontend/src/components/workspace/panel/workflow/form.tsx, frontend/src/components/workspace/panel/workspace-panel.tsx
- Update workflow execution UI to hit workflow executions endpoint
- Use json viewer 
- Manual QA, able to run from UI
=> feat(ui): Update workflow execution UI to hit workflow executions endpoint + use json viewer 

frontend/package.json, frontend/pnpm-lock.yaml, frontend/src/components/workspace/panel/udf-panel.tsx, frontend/src/components/workspace/panel/workflow/controls.tsx, frontend/src/lib/udf.ts, tracecat/api/app.py, tracecat/dsl/validation.py
- Update showing validation errors in action (udf) panel
- Show errors as YAML
- Add some general error handling
=> feat(ui): Update validation for action panel

frontend/src/components/nav/workflow-nav.tsx, frontend/src/components/workspace/panel/udf-panel.tsx
- Replace workflow run editor with monaco editor
- udf action panel: remove minimap and make scrollbars thinner
=> feat(ui): Replace workflow run editor with monaco editor

frontend/src/components/jsonschema-table.tsx, frontend/src/components/workspace/panel/udf-panel.tsx, frontend/src/lib/jsonschema.ts
=> feat(ui): Add secret schema + hover info to action panel schema section 

frontend/src/app/workflows/[workflowId]/executions/nav.tsx, frontend/src/client/schemas.gen.ts, frontend/src/components/nav/workflow-nav.tsx, frontend/src/components/ui/alert-dialog.tsx, frontend/src/components/workspace/canvas/canvas.tsx, frontend/src/components/workspace/canvas/trigger-node.tsx, frontend/src/components/workspace/panel/trigger-panel.tsx, frontend/src/lib/hooks.ts, frontend/src/lib/time.ts, tracecat/api/app.py, tracecat/config.py, tracecat/identifiers/schedules.py, tracecat/identifiers/workflow.py
- Add custom hooks for schedules CRUD
- Update node and panel UI
- Set vertical layout on each time the workflow loads
=> feat: Update schedule management UI

tracecat/db/schemas.py
- Use JSONB over JSON. More perf
=> feat(engine): Use JSONB instead of JSON

frontend/src/components/nav/workflow-nav.tsx, frontend/src/components/workspace/canvas/canvas.tsx, frontend/src/components/workspace/canvas/trigger-node.tsx, frontend/src/components/workspace/canvas/udf-node.tsx, frontend/src/components/workspace/catalog/udf-catalog.tsx, frontend/src/components/workspace/panel/udf-panel.tsx, frontend/src/components/workspace/panel/workspace-panel.tsx, frontend/src/lib/time.ts, frontend/src/lib/workflow.ts, tracecat/api/app.py
- Better error message for no workflow definition
- Fix graph layout and positioning
- Disable `run` button if not committed yet. We should probably change this to be 1 button.
- Update some function names
=> fix(ui): Graph layout and positioning fix + some UX

playbooks/enrichment/triage-using-llms.yml, playbooks/threat_intel/virustotal-to-email.yml
Issue #255 
As user base grows, similar sneaky bugs will eventually be factored out.
=> fix(playbooks): Update virustotal action  namespace

frontend/src/client/schemas.gen.ts, frontend/src/client/services.gen.ts, frontend/src/client/types.gen.ts, frontend/src/components/copy-button.tsx, frontend/src/components/jsonschema-table.tsx, frontend/src/components/nav/workflow-nav.tsx, frontend/src/components/workspace/canvas/canvas.tsx, frontend/src/components/workspace/panel/trigger-panel.tsx, frontend/src/components/workspace/panel/udf-panel.tsx, frontend/src/components/workspace/panel/workflow/form.tsx, frontend/src/lib/hooks.ts, frontend/src/lib/utils.ts, frontend/src/lib/workflow.ts, frontend/src/providers/workflow.tsx, tracecat/api/app.py, tracecat/dsl/common.py, tracecat/identifiers/__init__.py, tracecat/workflow/definitions.py, tracecat/workflow/models.py
=> fix(ui): Fix editing actions and other small issues

tracecat/actions/integrations/__init__.py, tracecat/actions/integrations/iam/__init__.py, tracecat/actions/integrations/iam/okta.py
- Adds iam directory for Identity & Access Management integrations
- Adds Okta integration with the following actions:
- Suspend user
- Unsuspend user
- Expire active user sessions
N/A
N/A
Was tested against a live Okta environment, all actions work as expected.
=> feat(integration): Okta integration (user management and sessions)

Dockerfile.dev, docker-compose.dev.yml
- Create standalone `Dockerfile.dev` and `docker-compose.dev.yml`
- Invoke using `docker compose -f docker-compose.dev.yml up`
- Avoids image/build clashes with prod docker setup, use `docker restart tracecat_worker` to reflect changes in the worker (doesn't have hot reload)
=> build: Add dev Dockerfile and docker-compose yml

tracecat/dsl/workflow.py
- Treat child workflkow exceptions as `DSLExecutionError` objects when using `FailStrategy.ISOLATED`. 
- This fixes an issue with `asyncio.gather(..., return_exceptions=True)` returning exceptions to the parent workflow, which throws an error in the Temporal converter because `ChildWorkflowError` is not serializable
- Returning exceptions this way does not count as a failure state, which means the parent workflow returns successfully
=> feat(engine): Return exceptions from child workflows as DSLExecutionError objects

frontend/Dockerfile.prod, frontend/docker/entrypoint.sh, frontend/public/runtime-config.js, frontend/src/app/layout.tsx, frontend/src/lib/api.ts
- Allows passing environment variables to UI client side code
- We pass $API_URL to allow building the UI image once and deploying with any backend url
=> feat(ui): Add runtime client side api config

tests/unit/test_functions.py, tracecat/expressions/functions.py
- Add new function to convert an ndjson string e.g. `{"a": 1}\n{"b": 2}` into a list of dicts
- Also removed `_` to denote "private" function (inconsistent usage)
- Added unit tests
- Usage `{{ FN.deserialize_ndjson(...) }}`
=> feat(integration): Add deserialize ndjson function

tests/unit/test_workflows.py, tracecat/dsl/workflow.py
- Add missing expression evaluation on non-loop child workflow path
- Added corresponding test to verify such behavior
=> fix(engine): Evaluate expressions on non-loop child workflow path

frontend/src/app/workspaces/[workspaceId]/settings/account/page.tsx, frontend/src/app/workspaces/[workspaceId]/settings/general/page.tsx, frontend/src/app/workspaces/[workspaceId]/settings/layout.tsx, frontend/src/app/workspaces/[workspaceId]/settings/loading.tsx, frontend/src/app/workspaces/[workspaceId]/settings/sidebar-nav.tsx, frontend/src/app/workspaces/page.tsx, frontend/src/components/auth/reset-password-form.tsx, frontend/src/components/auth/update-email-form.tsx, frontend/src/components/auth/update-password-form.tsx, frontend/src/components/auth/user-details-table.tsx, frontend/src/lib/hooks.ts, tracecat/auth/schemas.py
- Allow users to update their email
- Allow users to update their password
- Updated some settings layout and styles
=> feat(ui): Implement change email and password

docs/quickstart.mdx
=> fix(docs): Bullet point formatting

frontend/src/components/workspaces/workspace-members-table.tsx
=> refactor(ui): Disable change role as it's not available yet

docs/quickstart.mdx
=> fix(docs): Remove comma

frontend/src/config/udfs.ts
=> fix(ui): Add missing etl namespace

frontend/src/lib/hooks.ts, frontend/src/lib/utils.ts, frontend/src/lib/workflow.ts, frontend/src/types/schemas.ts
=> refactor(ui): Cleanup legacy types and hooks that are unused or replaced by openapi-ts client types

tracecat/api/app.py
=> fix(engine): No need to pass session into create default admin user

deployments/aws/ec2/variables.tf, docker-compose.yml, docs/self-hosting/deployment-options/docker-compose.mdx, docs/self-hosting/updating.mdx, tracecat/__init__.py
=> release: Bump version to 0.7.2

frontend/src/components/nav/user-nav.tsx
=> fix(ui): Link to GitHub repo in settings

tracecat/api/routers/schedules.py
=> fix(engine): Pass schedule params to trigger_input

frontend/src/components/dashboard/create-workflow-button.tsx
Self explanatory
manual qa - observe correct redirect
=> fix(ui): Fix redirect url after creating workflow from yaml

frontend/src/app/workspaces/[workspaceId]/workflows/[workflowId]/page.tsx, frontend/src/app/workspaces/[workspaceId]/workflows/layout.tsx, frontend/src/app/workspaces/layout.tsx, frontend/src/components/workbench/panel/workbench-panel.tsx, frontend/src/components/workbench/workbench.tsx
Self explanatory
https://github.com/user-attachments/assets/e4a15b79-28db-4b76-94d2-428104634800
=> fix+refactor(ui): Fix canvas layout overflow + rename workbench panel component for clarity

frontend/src/providers/workflow.tsx
- Direct user to mouseover the commit button to view commit error
- Make toast title more specific
=> feat(ui): More informative validaiton error toast

frontend/src/components/executions/event-details.tsx
- Make workflow runs jsons collapsed by default
=> feat(ui): Collapse JSON viewer by default

frontend/src/components/auth/user-details-table.tsx, frontend/src/components/nav/user-nav.tsx, frontend/src/components/workspaces/workspace-members-table.tsx, frontend/src/providers/workspace.tsx
- Implement change user role
- Enable user nav component + rename to "Manage members"
- Fix issue where null/undefined was being incorrectly handled when showing user account table
=> feat(ui): Implement change user role

tracecat/dsl/workflow.py
=> fix(engine): Add missed context locator

tracecat/expressions/core.py, tracecat/expressions/parser/validator.py
- Fixes error in validating `for_each`
- Added validation error locator to `ExprValidator`
Manual QA, able to commit and run reshape with for loop
=> fix(engine): Fix for loop validation

tracecat/actions/core/http.py
Fixes the JSON parse error for HTTP 204 statuses
=> fix: Allow http 204 error

tracecat/actions/core/http.py
=> feat(engine): Handle http status code 204

deployments/aws/ec2/variables.tf, docker-compose.yml, docs/self-hosting/deployment-options/docker-compose.mdx, docs/self-hosting/updating.mdx, tracecat/__init__.py
Autoformatter formatted a few lines here
=> release: Bump to 0.8.3

docs/self-hosting/updating.mdx
=> docs: Fix code style in steps

frontend/src/components/nav/workbench-nav.tsx
The trigger window was showing up when you click the button even though the button appears disabled.
=> fix(ui): Prevent manual trigger window from showing when button is disabled

.github/workflows/test-python.yml
=> ci(engine): Include playbooks in ci tests

playbooks/enrichment/triage-using-llms.yml, tracecat/workflow/management/management.py
- Fix missing control flow statements during workflow import
- Fix playbook validation error
- Tested that was able to import a workflow and run actions conditionally
=> fix(engine): Missing control flow in workflow import

pyproject.toml, tracecat/actions/integrations/__init__.py, tracecat/actions/integrations/database/__init__.py, tracecat/actions/integrations/database/mongodb.py
This PR adds an integration for MongoDB. This integration allows you to query a MongoDB instance.
By supplying a database name, collection name, search field and search value, you can return either the entire resulting document, or by supplying a comma-separated list of fields, you can return specific fields from the document.
1. Verify code is accurate 
2. Verify functionality of integration (MongoDB can be trialed for free)
=> feat(integration): Add mongodb doc find one getter 

.env.example, docker-compose.dev.yml, docker-compose.yml, pyproject.toml, registry/tracecat_registry/base/core/llm.py, tracecat/api/app.py, tracecat/config.py, tracecat/llm.py, tracecat/registry/client.py, tracecat/secrets/secrets_manager.py
- Add `ollama` docker compose service
- Add model options `llama3.2` and `llama3.2:1b` to AI action
=> feat(engine): Extend AI action with Ollama

frontend/src/components/registry/registry-actions-table.tsx, frontend/src/components/registry/registry-repos-table.tsx, frontend/src/components/table/column-header.tsx, frontend/src/components/table/faceted-filter.tsx
- Make filterable fields inferred from the data
- Standardize some font sizes
=> feat(ui): Add registry action table filters

frontend/src/components/registry/delete-registry-action.tsx, frontend/src/components/registry/registry-actions-table.tsx, frontend/src/lib/hooks.ts, tracecat/registry/actions/router.py
- Add registry action delete with confirmation dialog
Probably could have been shorter. should probably reduce amount of FE boilerplate at some point
=> feat(engine+ui): Add registry action delete

tracecat/registry/actions/service.py, tracecat/registry/repository.py
- Implement diffing to account for additions and deletions
- We need to manually delete the modules from `sys.modules` before we reload the module
- Account for likely concurrency issues when a sync is performed while actions are being looked up
=> feat(engine): Improve registry actions service sync diffing logic

frontend/src/app/registry/actions/edit/page.tsx, frontend/src/app/registry/actions/new/page.tsx, tracecat/registry/actions/router.py
Improve error messages in edit/new registry action forms
=> feat: Improve error message in new/edit registry action forms

tracecat/api/app.py, tracecat/registry/repositories/service.py
=> refactor(engine): Remove sync on start

registry/tracecat_registry/templates/crowdstrike/list_detects.yml
https://www.falconpy.io/Service-Collections/Detects.html#querydetects
=> fix(integration): GetQueryDetect wrong operation ID and args

deployments/aws/fargate/rds.tf
Fixes plan error when no snapshots exists (i.e. cold start Terraform apply)
=> ci(infra): Fix issue with no snapshot terraform apply

tracecat/registry/repository.py
Allow users to sync yaml template actions from a remote repository
=> feat(engine): Sync template actions from remote repository

alembic/env.py, pyproject.toml, tracecat/db/engine.py
=> fix: Revert changes to migration script

registry/tracecat_registry/templates/jira/create_issue.yml, registry/tracecat_registry/templates/jira/update_issue.yml
Incorrect reference of secrets (it.s SECRETS. not secrets.) and 2. name for the formula `to_base64` not `str_to_b64`
=> fix(integration): Incorrect Jira referencing secret

frontend/src/client/schemas.gen.ts, frontend/src/client/types.gen.ts, frontend/src/components/executions/event-details.tsx, tracecat/dsl/action.py, tracecat/dsl/models.py, tracecat/dsl/workflow.py, tracecat/registry/actions/router.py, tracecat/registry/client.py, tracecat/registry/executor.py, tracecat/workflow/executions/models.py
Give this a more meaningful name, now that actions can be udfs or template actions
=> refactor: Rename UDFActionInput to RunActionInput

frontend/src/components/workbench/canvas/canvas.tsx
- Make edges smoothstep (radius adjustable)
- Increase vertical node padding
=> feat(ui): Smoothstep edges

frontend/src/client/schemas.gen.ts, frontend/src/client/types.gen.ts, frontend/src/components/executions/event-details.tsx, frontend/src/components/workbench/panel/udf-panel-tooltips.tsx, frontend/src/components/workbench/panel/udf-panel.tsx, tracecat/dsl/action.py, tracecat/dsl/graph.py, tracecat/dsl/models.py, tracecat/types/api.py, tracecat/workflow/executions/models.py, tracecat/workflow/management/management.py
- Allow configuration of a delay at the start of any action
=> feat: Add action start delay

tracecat/logger/_logger.py
- Make secondary info i.e. timestamp, PID, module/fn name and line no grey
- Simplify timestamp format
=> feat(engine): Improve logger colors + formatting

tracecat/auth/users.py
- Add default email and password as fallback
=> feat: Add default email + pw as fallback

docs/integrations/expressions.mdx, docs/mint.json, tracecat/expressions/functions.py
- Refactor lambda functions into functions with single line docstrings
- Maybe there's a better way to do this but this will do for now
- Unit tests pass locally
=> refactor: Refactor expression functions to be more docs friendly

registry/tracecat_registry/base/core/http.py
=> fix(integration): Assignment error if jwt is specified but headers none

frontend/src/components/jsonschema-table.tsx
=> feat(ui): Sort schema by required then alphabet

frontend/src/app/workspaces/[workspaceId]/workflows/[workflowId]/executions/page.tsx
Self explanatory
https://github.com/user-attachments/assets/a97ca541-7e96-4f4b-ad13-a561d9b31cf0
=> feat(ui): Allow independent scrolling of workflow runs columns

frontend/src/components/copy-button.tsx, frontend/src/components/workbench/canvas/action-node.tsx, frontend/src/components/workbench/canvas/trigger-node.tsx
- Add copy button next to title + add tooltip
- Remove unused dropdown items
- Remove events bell icons
=> feat+refactor(ui): Improve copy button + some cleanup

frontend/src/components/workbench/panel/action-panel.tsx, frontend/src/components/workbench/panel/workflow-panel.tsx
- Add tabs for workflow panel
- Unsure about panel top padding size
https://github.com/user-attachments/assets/f238fa38-61bf-4996-a71f-c61dbaaf7c20
=> feat(ui): Add workflow panel tabs

frontend/src/components/workbench/panel/action-panel-tooltips.tsx, frontend/src/components/workbench/panel/action-panel.tsx
https://github.com/user-attachments/assets/3f972cc9-43e7-4831-be7e-21453c97942c
=> refactor(ui): Move retry policy into its own tab

tests/unit/test_expressions.py, tracecat/api/app.py, tracecat/dsl/common.py, tracecat/dsl/models.py, tracecat/dsl/validation.py, tracecat/dsl/workflow.py, tracecat/expressions/parser/evaluator.py, tracecat/expressions/parser/grammar.py, tracecat/webhooks/dependencies.py, tracecat/webhooks/models.py, tracecat/webhooks/router.py, tracecat/workflow/executions/models.py, tracecat/workflow/executions/service.py, tracecat/workflow/management/management.py, tracecat/workflow/management/models.py, tracecat/workflow/management/router.py
- Move webhooks into a module
- Webhook accepts arbitrary JSON
- Webhook accepts ndjson
- You can reference `TRIGGER` directly, without including a jsonpath
=> feat+refactor(engine): Cleanup and improve webhooks

tests/unit/test_workflows.py, tracecat/expressions/core.py, tracecat/expressions/parser/evaluator.py, tracecat/registry/actions/models.py, tracecat/registry/actions/router.py, tracecat/registry/client.py
=> feat(engine): Add traceback info and error kind to error messages

registry/tracecat_registry/integrations/checkpoint.py, registry/tracecat_registry/integrations/limacharlie.py, registry/tracecat_registry/integrations/microsoft_graph.py, registry/tracecat_registry/integrations/wiz.py
- Drop `await`
- Get secret.get("SECRET_KEY") not secret.get("secret_name")
=> fix(integrations): Incorrect `secrets` API usage in get token actions

frontend/src/components/workbench/panel/action-panel.tsx
- Add save states
- Show save errors
- Add cmd/ctrl + s to save
- We still save when the panel becomes unfocused
https://github.com/user-attachments/assets/a2a39052-6264-46ee-b474-0af6296a13e5
=> feat(ui): Improve action panel save

frontend/src/components/workbench/canvas/selector-node.tsx
=> feat(ui): Use skeleton for selector loading state

frontend/src/components/workbench/canvas/action-node.tsx, frontend/src/lib/workflow.ts
https://github.com/user-attachments/assets/a1c05d56-415a-42d6-9d2c-97dd0bb61fd8
=> feat(ui): Add link to open child workflow from builder node

frontend/src/client/schemas.gen.ts, frontend/src/client/types.gen.ts, frontend/src/components/executions/event-details.tsx, tracecat/workflow/executions/models.py, tracecat/workflow/executions/service.py
https://github.com/user-attachments/assets/1127fc6f-1316-4f82-a10b-70bb48d2d1a8
=> feat: Add go to parent workflow run

pyproject.toml, tests/unit/test_expressions.py, tracecat/dsl/workflow.py, tracecat/expressions/functions.py, tracecat/expressions/parser/evaluator.py, tracecat/expressions/parser/grammar.py, tracecat/expressions/parser/validator.py
- Remove jsonpath function expr
- Enable full `jsonpath_ng` syntax
- Added more unit tests. See tests for examples of syntax usage
=> feat(engine): Enable full jsonpath_ng syntax + remove jsonpath function expr

registry/tracecat_registry/base/core/transform.py, tests/data/workflows/unit_transform_filter_dict.yml, tests/data/workflows/unit_transform_filter_function.yml, tests/unit/test_expressions.py, tests/unit/test_functions.py, tracecat/expressions/functions.py
- Update filter functions
- Delete build reference table
- Add tests for all (most?) function exprs
=> feat(engine): Update filter functions + delete build reference table

frontend/src/components/organization/org-secret-create.tsx, frontend/src/components/secrets/create-secret-tooltip.tsx, frontend/src/components/workspaces/add-workspace-secret.tsx
- Update secret tooltip in org and workspace
=> feat(ui): Update create secret tooltip

tests/unit/test_expressions.py, tracecat/registry/client.py, tracecat/workflow/executions/service.py
=> feat(engine): Add json decode error handling

registry/tracecat_registry/templates/crowdsec/search_ip_address.yml, registry/tracecat_registry/templates/crowdsec/unblock_ip_address.yml, registry/tracecat_registry/templates/wazuh/update_agents.yml
Change of method (CrowdSec URL)
=> fix(integration): add crowdsec url in secrets

tracecat/expressions/functions.py
Functions are not grouped by usage category. This reorganizes the functions and adds inline comments for each section.
=> refactor(engine): Reorganize functions

deployments/aws/fargate/locals.tf, deployments/aws/fargate/variables.tf, tracecat/config.py, tracecat/workflow/executions/service.py
- Add `TEMPORAL__CLIENT_RPC_TIMEOUT`
- Add tf variables
- `temporal_client_rpc_timeout`
- `temporal_log_level`
=> feat+ci(infra): Add temporal variables and logging patches from staging

tests/unit/test_functions.py, tracecat/expressions/functions.py
=> feat(engine): Replace jsonpath with lambda in intersect function

pyproject.toml, tests/conftest.py, tests/playbooks/test_playbooks.py, tests/registry/test_templates.py, tests/unit/test_auth.py, tests/unit/test_concurrency.py, tests/unit/test_error_handling.py, tests/unit/test_export.py, tests/unit/test_expressions.py, tests/unit/test_registry.py, tests/unit/test_sandbox.py, tests/unit/test_template_actions.py, tests/unit/test_workflows.py
- pytest-asyncio keeps having event loop issues
=> test: Replace pytest-asyncio with pytest-anyio

frontend/src/app/workspaces/[workspaceId]/workflows/[workflowId]/executions/layout.tsx, frontend/src/lib/hooks.tsx
- Add polling for workflow runs history (2s default). We will make this configurable from the UI at some point.
=> feat(ui): Add polling for workflow runs history

registry/tracecat_registry/templates/virustotal/list_comments.yml
This PR aligns the title and description naming for the VirusTotal list_comments template. It also aligns with the naming used in the Control Flow tutorial in the documentation.
=> refactor(integration): Consistent naming in VirusTotal list_comments template

tracecat/auth/credentials.py, tracecat/auth/dependencies.py, tracecat/testing/registry.py, tracecat/workflow/executions/router.py, tracecat/workflow/management/router.py
- Cleanup unused permutations of role dependencies
=> refactor(engine): Consolidate and cleanup role acl dependencies

registry/tracecat_registry/templates/wazuh/clear_rootcheck.yml, registry/tracecat_registry/templates/wazuh/get_last_scan_rootcheck.yml, registry/tracecat_registry/templates/wazuh/run_rootcheck.yml
This Pull Request introduces three new actions to streamline the management of Wazuh agents by automating key tasks related to the rootcheck feature. These actions enable efficient handling of scans that detect unauthorized system-level changes, making Wazuh integrations more robust and user-friendly.
Initiates a rootcheck scan on specified Wazuh agents and retrieves the results for analysis.
Clears all previous rootcheck scan results from specified Wazuh agents, allowing a clean state for new scans.
Fetches the timestamp of the latest rootcheck scan performed on specified Wazuh agents.
=> feat(integration): rootcheck wazuh

frontend/src/components/workbench/canvas/action-node.tsx
Fixes issue where state not updated in action node missing inputs
=> fix(ui): Show action node missing inputs correctly

frontend/src/app/registry/actions/edit/page.tsx, frontend/src/app/registry/actions/new/page.tsx, frontend/src/components/editor/dynamic.tsx, frontend/src/components/editor/editor.tsx, frontend/src/components/nav/workbench-nav.tsx, frontend/src/components/workbench/panel/action-panel.tsx, frontend/src/components/workbench/panel/workflow-panel.tsx
- Introduce DynamicCustomEditor component that loads CustomEditor dynamically only. Returns blank component if on server side
- Make all uses of CustomEditor dynamic
=> fix(ui): Make all usage of CustomEditor dynamic

frontend/src/components/executions/event-details.tsx, frontend/src/components/executions/nav.tsx, frontend/src/components/executions/testdecode.ts, frontend/src/lib/event-history.ts
- Fix broken parsing of related scheduled executions
- Remove unused file
=> fix(ui): Fix and cleanup related workflow runs

registry/pyproject.toml, registry/tracecat_registry/integrations/ansible.py, registry/tracecat_registry/integrations/boto3.py, registry/tracecat_registry/integrations/s3.py, registry/tracecat_registry/templates/ansible/run_playbook_from_s3.yml
=> feat(integration): S3 getter and Ansible playbook runner

tests/unit/test_registry.py
- Add check that lists all registry actions. If a registry action is malformed (e.g. a template's steps cannot be parsed correctly) it will fail
=> test: Check that we can list all registry actions

tests/data/test_actions/test_executor_functions.py, tests/unit/test_executor.py, tracecat/registry/executor.py
- Pull secrets on each template action step
- Only pull secrets that have not already been pulled but checking secret context
=> fix(engine): Pull secrets for template action steps

tests/unit/test_functions.py, tracecat/expressions/functions.py
=> feat(engine): Add FN.range

tracecat/dsl/workflow.py
- Return proper coros
- Use start child workflow over execute
=> feat(engine): Attempt to block less in child workflow loop

tracecat/dsl/common.py
Merge from staging
Fix issue uploading workflows with error paths
=> fix(engine): Consdier edge components when building graph

tracecat/dsl/workflow.py
- Invoke child workflow coroutine properly
=> feat(engine): Yield control in hot loop

deployments/aws/ecs/ecs-api.tf, deployments/aws/ecs/ecs-caddy.tf, deployments/aws/ecs/ecs-executor.tf, deployments/aws/ecs/ecs-temporal-ui.tf, deployments/aws/ecs/ecs-temporal.tf, deployments/aws/ecs/ecs-ui.tf, deployments/aws/ecs/ecs-worker.tf
- Graviton instances
- Multiple workers (n=2) with 50% spot
- Health checks for API, worker, and executor
=> ci(infra): Optimize ECS

frontend/package.json, frontend/pnpm-lock.yaml, frontend/src/components/color-picker.tsx, frontend/src/components/dashboard/dashboard-table.tsx, frontend/src/components/dashboard/workflow-tags-sidebar.tsx, frontend/src/components/dashboard/workflows-dashboard.tsx, frontend/src/lib/hooks.tsx
- **build(ui): Add react-colorful 5.6.1**
- **ui: Add color picker**
- **ui: Add tags to workflows dashboard**
=> feat(ui): Implement workflow tags UI

.github/workflows/build-push-images.yml
Cherry-pick 8417ad6 from merge commit into main as it was originally merged into staging.
=> ci(build): Multi-platform runner builds (#612)

tracecat/authz/service.py, tracecat/organization/service.py, tracecat/registry/actions/service.py, tracecat/registry/repositories/service.py, tracecat/secrets/service.py, tracecat/service.py, tracecat/tags/service.py, tracecat/workflow/management/definitions.py, tracecat/workflow/management/management.py, tracecat/workflow/schedules/service.py, tracecat/workflow/tags/service.py, tracecat/workspaces/service.py
- Reduce a lot of boilerplate code and standardize BaseService
=> refactor(engine): Services inherit from BaseService

docs/api-reference/reference/editor/list-actions.mdx, docs/api-reference/reference/editor/list-functions.mdx, docs/api-reference/reference/organization/delete-org-member.mdx, docs/api-reference/reference/organization/delete-session.mdx, docs/api-reference/reference/organization/list-org-members.mdx, docs/api-reference/reference/organization/list-sessions.mdx, docs/api-reference/reference/organization/update-org-member.mdx, docs/api-reference/reference/registry-repositories/sync-executor-from-registry-repository.mdx, docs/api-reference/reference/registry-repositories/sync-registry-repository.mdx, docs/api-reference/reference/tags/create-tag.mdx, docs/api-reference/reference/tags/delete-tag.mdx, docs/api-reference/reference/tags/get-tag.mdx, docs/api-reference/reference/tags/list-tags.mdx, docs/api-reference/reference/tags/update-tag.mdx, docs/api-reference/reference/workflows/add-tag.mdx, docs/api-reference/reference/workflows/list-tags.mdx, docs/api-reference/reference/workflows/remove-tag.mdx, docs/cheatsheets/functions.mdx, docs/cheatsheets/integrations.mdx, docs/mint.json, docs/openapi.yml, justfile
=> chore(docs): Update API and cheatsheet docs

env.sh
Added error handling for the script to make a smoother install process.
Found some issues in other distributions than Ubuntu that will give good error messages and exit before writing to file. 
Solves: https://github.com/TracecatHQ/tracecat/issues/653
=> build: Improve error handling in `env.sh` #653

frontend/src/components/dashboard/dashboard-table.tsx, frontend/src/components/workbench/panel/workflow-panel.tsx
=> feat(ui): Implement workflow alias UI

frontend/src/components/workbench/canvas/action-node.tsx
- Show the alias of the child workflow in place of "Open workflow" in the action node.
- Putting a badge below `core.workflow.execute`. Thought it looked off, but open to suggestions
=> feat(ui): Add workflow alias to action nodes

tests/unit/test_workflows.py, tracecat/dsl/action.py, tracecat/executor/client.py, tracecat/types/exceptions.py
Clearer indication of responsibilities
=> refactor(engine): Rename ActionExecutionError to ExecutorClientError

registry/tracecat_registry/integrations/ldap3.py
- Removes redundant escape_rdn calls since auto_escape=True handles attribute/DN escaping
- Keeps escape_filter_chars only for search filters where LDAP injection is a risk
- Fixes bind DN authentication issues caused by over-escaping
=> fix(integration): Remove unnecessary DN escaping in LDAP client

frontend/src/components/workbench/panel/workflow-panel.tsx, tests/unit/test_workflows.py
=> feat(ui): Add error handler configuration to workflow panel

frontend/src/components/nav/workbench-nav.tsx, frontend/src/components/workbench/canvas/trigger-node.tsx, frontend/src/components/workbench/panel/workflow-panel.tsx
- Drop status section and dropdown in workflow trigger
- Drop field description for alias to make consistent with other fields UI
- Added tooltip (same description also shows if no alias is added)
- Renamed "Error handler" to "Error workflow"
=> chore(ui): Delete unused elements in workflow trigger and alias

tests/unit/test_dependencies.py, tracecat/auth/dependencies.py
Make `require_auth_type_enabled` more testable and add tests
=> refactor+test: Improve testing for auth config dep

tracecat/auth/saml.py
~NOTE: We need config migrations before this should be merged~ Unblocked by #730 
- Migrate from `config.SAML_IDP_METADATAURL` to `saml_idp_metadata_url`
- Add fallback
=> feat(app): Get `saml_idp_metadata_url` from settings service

deployments/aws/ecs/variables.tf, deployments/aws/variables.tf, docker-compose.yml, docs/self-hosting/deployment-options/docker-compose.mdx, docs/tutorials/updating.mdx, tracecat/__init__.py
- **Default to empty string for undefined form values**
- **release: Bump 0.20.1**
=> chore: Merge 0.20.1 hotfix into main

docs/cheatsheets/functions.mdx, tests/unit/test_functions.py, tracecat/expressions/functions.py
=> feat(engine): Add set difference function and tests

frontend/src/client/schemas.gen.ts, frontend/src/client/types.gen.ts, tests/unit/test_registry.py, tracecat/api/common.py, tracecat/dsl/scheduler.py, tracecat/git.py, tracecat/identifiers/__init__.py, tracecat/registry/repository.py, tracecat/settings/service.py, tracecat/ssh.py, tracecat/types/exceptions.py
Add methods to git and ssh modules In preparation for adding ray runtime env implementation, with some additional cleanup
=> feat(engine): Add and update git and ssh modules

registry/pyproject.toml, registry/tracecat_registry/integrations/tenable_nessus.py, registry/tracecat_registry/templates/tenable_nessus/list_vulnerabilities.yml
- https://github.com/tenable/pyTenable/blob/main/tests/nessus/test_scans.py
- https://pytenable.readthedocs.io/en/stable/api/nessus/scans.html#tenable.nessus.scans.ScansAPI.details
=> feat(integrations): Tenable nessus scans

deployments/aws/ecs/variables.tf, deployments/aws/variables.tf, docker-compose.yml, docs/self-hosting/deployment-options/docker-compose.mdx, docs/tutorials/updating.mdx, tracecat/__init__.py
Tracecat now supports remote workers.
=> release: 0.21.0

alembic/versions/db3c91261770_add_temporal_search_attributes.py, frontend/src/app/workspaces/layout.tsx, frontend/src/components/executions/event-history.tsx, frontend/src/components/nav/workbench-nav.tsx, frontend/src/components/workbench/canvas/canvas.tsx, frontend/src/components/workbench/panel/trigger-panel.tsx, frontend/src/lib/hooks.tsx, frontend/src/providers/builder.tsx, tracecat/workflow/executions/service.py
=> feat(ui): Preparations for compact builder runs 

alembic/versions/f92c80ef8c9d_use_uuids_for_workflows.py, frontend/next-env.d.ts, tracecat/db/schemas.py, tracecat/dsl/common.py, tracecat/identifiers/workflow.py, tracecat/webhooks/dependencies.py, tracecat/workflow/actions/router.py, tracecat/workflow/executions/router.py, tracecat/workflow/management/definitions.py, tracecat/workflow/management/management.py, tracecat/workflow/management/router.py, tracecat/workflow/schedules/service.py
- **Add migraiton**
- **Migrate db schema to use UUID as canonical ID**
=> feat(engine): Migrate workflow ID schema

frontend/src/components/workbench/canvas/canvas.tsx
=> feat(ui): Right click to drop selector node

frontend/src/components/workbench/workbench.tsx
Repalce events sidebar toggle as it was kinda buggy
https://github.com/user-attachments/assets/eaab4681-20ac-4d5b-a484-25da934ab7a2
=> feat(ui): Replace sidebar toggle button

frontend/src/components/workbench/events/events-selected-action.tsx, frontend/src/components/workbench/events/events-sidebar.tsx, frontend/src/components/workbench/workbench.tsx
- Fix issue where overflows weren't being handled 
- Keep tabs at top when scrolling vertically through content
- Tabs scroll horizontally
=> fix(ui): Fix overflow and scroll behavior in events sidebar

frontend/src/client/schemas.gen.ts, frontend/src/client/types.gen.ts, frontend/src/components/code-block.tsx, frontend/src/components/executions/event-details.tsx, frontend/src/components/workbench/events/events-selected-action.tsx, tracecat/workflow/executions/common.py, tracecat/workflow/executions/models.py, tracecat/workflow/executions/service.py
=> feat(ui): Add event failure and error message to result

frontend/src/components/workbench/events/events-selected-action.tsx
Also cleaned up some of the UI elements
=> feat(ui): Show action status in input and result tabs

.github/workflows/test-python.yml, registry/tracecat_registry/base/core/http.py, tests/registry/test_core_http.py, tests/stress/server.py, tests/unit/test_functions.py, tracecat/expressions/functions.py
- Add `core.http_poll` 
- Restructure `core.http` modules so common http parameters can be reused
- Added unit tests
=> feat(engine): Add http polling action

frontend/src/components/workbench/events/events-workflow.tsx
https://github.com/user-attachments/assets/1462a7fd-2404-4fbb-b5a9-c1b19ad95308
=> fix(ui): Fix positioning of workflow status icon in UI

frontend/src/components/workbench/canvas/action-node.tsx
Fixes issue where having duplicate keys (or generally yaml parsing) errors would break the UI and users wouldn't be able to open workflows.
https://github.com/user-attachments/assets/3ace7ca7-e78b-47c7-96f7-d7e9e87ae2a8
=> fix(ui): Catch YAML parsing issues and show invalid configuration in the UI

tests/unit/test_functions.py, tracecat/expressions/functions.py
Small PR to add an url_decode function.
=> feat(integrations): Add `url_decode` function

frontend/package.json, frontend/pnpm-lock.yaml, frontend/src/components/workbench/events/events-selected-action.tsx, frontend/src/components/workbench/panel/action-panel.tsx
- ~There might be a bug in react18-json-view ([issue](https://github.com/YYsuni/react18-json-view/issues/66#issuecomment-2661661436)) where the first item in a list doesn't get the correct `NodeMeta` parent path. Please note while we wait on a fix.~ Fixed now
https://github.com/user-attachments/assets/8bf99bb9-8670-4ac8-8b5b-402b6ccc51c9
=> feat(ui): Make copy button in builder view copy jsonpath

frontend/src/components/workbench/panel/trigger-panel.tsx
- Removed hover card showing empty dict when you mouseover the schedule row
=> refactor(app): Remove schedule inputs hover card

frontend/src/components/auth/sign-in.tsx, frontend/src/lib/hooks.tsx
Throw this error instead of just showing blank sign up screen to make it obvious.
Addresses issues #867
=> feat(ui): Throw UI error if can't fetch AppInfo from backend

registry/tracecat_registry/base/core/http.py, tests/registry/test_core_http.py, tests/unit/test_workflows.py, tracecat/executor/client.py
- Add custom http error handlers, remove certain default boilerplate. Add more handlers as needed
(The trailing colon after the URL has been replaced with a full stop)
=> feat(core): Improve `core.http_request` error messages

registry/tracecat_registry/integrations/wazuh.py, registry/tracecat_registry/templates/harden/update_agents/wazuh.yml, registry/tracecat_registry/templates/tools/wazuh/active_response.yml
Issue: https://github.com/TracecatHQ/tracecat/issues/900
Addition of Wazuh integration:
- `update_agent`
- `active-response`
- `get-access-token`
Everything has been tested from the repository: https://github.com/aukfood/repo-tracecat-aukfood
=> feat(integrations): Wazuh update agents and active response

frontend/Dockerfile.prod
Fixes: JSON arguments recommended for ENTRYPOINT/CMD to prevent unintended behavior related to OS signals
=> build: Frontend dockerfile cmd json args

frontend/src/components/icons.tsx
=> feat(ui): Add icon for `core.require`

registry/tracecat_registry/core/table.py, tests/unit/test_tables_service.py, tests/unit/test_workflows.py, tracecat/tables/service.py
=> feat(core): Add lookup multiple rows action

.github/workflows/test-python.yml, pyproject.toml, tests/unit/test_podman.py
- **Add podman mark**
- **Use -m not podman**
=> test: Add podman pytest mark

frontend/src/components/workbench/panel/action-panel.tsx
Add preview of possible future interactions: MFA, forms,  approval.
=> feat(ui): Add future interactions

registry/tracecat_registry/templates/llm/experimental/alert_contextualizer.yml, registry/tracecat_registry/templates/llm/experimental/ioc_extractor.yml, registry/tracecat_registry/templates/llm/experimental/remediation_generator.yml
Experimental.
Adds 
`openai.guardduty.alert_contextualizer`
`openai.guardduty. ioc_extractor`
`openai.guardduty.remediation_generator`
=> feat(integrations): Add experimental openai guardduty agent

registry/tracecat_registry/templates/detect/lookup_user_by_email/okta.yml
- Wrap inputs.email with quotations
- Don't return the first element, but instead take .data and return the list
=> fix(integrations): Fix Okta user lookup query + result parsing

frontend/src/client/schemas.gen.ts, frontend/src/client/types.gen.ts, frontend/src/components/organization/org-settings-app.tsx, tracecat/settings/models.py, tracecat/workflow/executions/router.py
- **Add wf executions query limit, default 100**
- **Update openapi ts client**
- **Add setting to UI**
=> feat(ui): Add workflow executions query limit setting

deployments/aws/ecs/ecs-caddy.tf, deployments/aws/ecs/ecs-worker.tf, deployments/aws/ecs/ecs.tf, deployments/aws/ecs/variables.tf, deployments/aws/main.tf, deployments/aws/variables.tf
=> ci: Add prom metrics to fargate

registry/tracecat_registry/core/table.py
- By induction, since table service already tested.
- Also tested manually in UI
=> feat(actions): Add `update_row` and `delete_row` by ID actions

registry/tracecat_registry/templates/notify/add_comment/thehive.yml, registry/tracecat_registry/templates/notify/create_case/thehive.yml, registry/tracecat_registry/templates/notify/update_case/description/thehive.yml, registry/tracecat_registry/templates/notify/update_case/fields/thehive.yml, registry/tracecat_registry/templates/notify/update_case/status/thehive.yml
- `add_case`
- `add_case_comment`
- `update_case_description`
- `update_case_fields`
- `update_case_status`
=> feat(integrations): TheHive case templates

frontend/src/components/workbench/workbench.tsx
- CMD+E for events panel (left side)
- CMD+U for action panel (right side)
=> feat(ui): Add hotkeys to toggle events panel and action panel

tracecat/tables/service.py
Moving forward, as tables infrastructure may be eventually used by other services, it makes sense to expose a `BaseTablesService` with non-transactional methods so that other table-like services can be built with transaction guarantees. 
We need TablesService methods without commit() to handle transactions for case fields table management. 
- Split out TablesService into BaseTablesService, making methods call session.flush() instead of session.commit(). 
- This allows us to extend a CaseFieldsService from the base tables service and chain together methods within a transaction
- TablesService still functions the same -- it inherits from BaseTablesService and calls the replaced commit() and refresh() methods.
=> refactor(engine): Extract out BaseTablesService from TablesService

registry/tracecat_registry/core/cases.py
=> feat(registry): Add create/update case and create/update case comments UDFs

registry/tracecat_registry/integrations/slack_sdk.py
We were not handling responses from Slack SDK properly. It's an `AsyncSlackResponse` which is not directly serializable into a dict.
Ran `tools.slack_sdk.call_method` and `tools.slack_sdk.call_paginated_method` on `chat_postMessage` and `conversations_history` methods
=> fix(integrations): Slack response types

frontend/src/app/workspaces/[workspaceId]/cases/fields/page.tsx, frontend/src/app/workspaces/[workspaceId]/cases/layout.tsx, frontend/src/app/workspaces/[workspaceId]/cases/page.tsx, frontend/src/components/cases/case-categories.tsx, frontend/src/components/cases/case-description-editor.tsx, frontend/src/components/cases/case-panel-custom-fields.tsx, frontend/src/components/cases/case-panel-description.tsx, frontend/src/components/cases/case-panel-selectors.tsx, frontend/src/components/cases/case-panel-summary.tsx, frontend/src/components/cases/case-panel-view.tsx, frontend/src/components/cases/case-table-columns.tsx, frontend/src/components/cases/case-table-insert-button.tsx, frontend/src/components/cases/case-table.tsx, frontend/src/components/cases/editor.css, frontend/src/components/sliding-panel.tsx, frontend/src/components/tables/table-create-dialog.tsx, frontend/src/components/ui/input.tsx, frontend/src/components/ui/select.tsx, frontend/src/lib/rich-text-editor.test.ts, frontend/src/lib/rich-text-editor.ts
See commit history for full list
- **Add sheet title to sliding panel**
- **Fix menu plus button visibility**
- **Transparent bg + clean up styles**
- **Move onBlur handler into case description editor**
- **Add block spacing function**
- **Apply spacing to level 1 headings**
- **Remove select checkbox + add updated_at and formatted datetimes**
- **Show full dates in case table**
- **Show created at + updated at in case panel view**
- **Tighten up create table dialog**
- **Rearrange layout to use breadcrumbs**
- **Cleanup**
=> feat(ui): Improve case management UI

.env.example, docker-compose.dev.yml, docker-compose.yml, docs/self-hosting/deployment-options/docker-compose.mdx
=> ci: Parameterize public port

tracecat/cases/enums.py, tracecat/cases/models.py, tracecat/cases/router.py
We will add these back later. Currently this causes issues when running certain unit tests (weird?)
=> refactor(app): Drop case activity

frontend/src/components/cases/case-table.tsx, frontend/src/components/data-table/table.tsx
Save table state in local storage
https://github.com/user-attachments/assets/5e71e87b-f9e7-4486-b7e7-d7b45b483f59
=> feat(ui): Store table state in local storage

registry/tracecat_registry/core/cases.py, tests/registry/test_core_cases.py
- core.cases.create -> core.cases.create_case
- core.cases.update -> core.cases.update_case
=> refactor(registry)!: Add _case suffix to core.cases actions

frontend/src/components/cases/case-workflow-trigger.tsx
- Add link to open up the selected wf run in new tab
=> feat(ui): Add link to workflow in case workflow trigger

frontend/src/components/cases/case-table-columns.tsx, frontend/src/components/cases/case-table.tsx, frontend/src/components/dashboard/dashboard-table.tsx, frontend/src/components/data-table/table.tsx, frontend/src/components/data-table/toolbar.tsx, frontend/src/components/organization/org-members-table.tsx, frontend/src/components/organization/org-sessions-table.tsx, frontend/src/components/registry/registry-actions-table.tsx, frontend/src/components/registry/registry-repos-table.tsx, frontend/src/components/tables/tables-dashboard.tsx, frontend/src/components/workspaces/workspace-members-table.tsx, frontend/src/components/workspaces/workspace-secrets-table.tsx, frontend/src/lib/hooks.tsx
Add table row deletion, added to case managmeent
=> feat(ui): Add case table deletion

frontend/src/components/workbench/canvas/canvas.tsx, frontend/src/lib/hooks.tsx
https://github.com/user-attachments/assets/9f0785da-3fd1-4f52-97f6-1a601320a8b9
https://github.com/user-attachments/assets/2bc34a14-9a3d-4fc6-8e0e-645c9fe7b589
=> fix(ui): Refetch actions on delete

frontend/src/components/ui/resizable.tsx
- Make the drag handles in the panel easier to grab by making the transparent handles wider
=> feat(ui): Make transparent border handles wider

frontend/src/app/page.tsx, frontend/src/components/workbench/canvas/action-node.tsx, frontend/src/components/workbench/events/events-workflow.tsx
- **Adjust logo tracking**
- **Cleanup action toolbar capitalization**
- **Add view input and result to events sidebar menu**
- **Make events table look more like a timeline**
- **Make execution ID tooltip less sensitive**
=> feat(ui): Improve events timeline styles + add view input/result

frontend/src/components/loading/spinner.tsx, frontend/src/components/nav/workbench-nav.tsx, frontend/src/components/workbench/events/events-workflow.tsx, frontend/src/lib/hooks.tsx
- Split run button into direct run and run with payload
- Adjust workflow event sidebar status icons
- Move createExecution error handling into hook
=> feat(ui): Navbar updates

frontend/src/components/nav/workbench-nav.tsx, frontend/src/providers/workflow.tsx, tracecat/webhooks/dependencies.py
- **Remove top margin from TabsContent**
- **Remove workflow status check in webhook**
- **Remove workflow status from ui**
https://github.com/user-attachments/assets/616bf791-e065-4491-a5af-495347d81065
=> refactor(ui): Drop workflow status checks in webhook and visuals from UI

frontend/src/client/schemas.gen.ts, frontend/src/client/types.gen.ts, frontend/src/components/dashboard/create-workflow-button.tsx, frontend/src/components/dashboard/dashboard-table.tsx, frontend/src/components/data-table/column-header.tsx, frontend/src/components/data-table/table.tsx, frontend/src/components/data-table/view-options.tsx, frontend/src/components/nav/workbench-nav.tsx, frontend/src/components/ui/button.tsx, frontend/src/components/ui/table.tsx, frontend/src/lib/utils.ts, tracecat/workflow/management/management.py, tracecat/workflow/management/models.py, tracecat/workflow/management/router.py
- **Drop separator from view filter**
- **No ring**
- **Set focus-visible:ring-0 on all buttons**
- **Make workflow table create button consistent with other buttons**
- **Slim down table rows and header**
- **Clean up save workflow tooltip**
- **Cleanup unused imports**
- **Disable hiding in data table column header if can't be hidden**
- **Pass initial column visibility to data table**
- **Fetch latest workflow definition in list workflows endpoint**
- **Add capitalizeFirst util function**
- **Improve workflow table filtering**
- **Adjust unsaved style**
- Added tooltips when hovering over relative time
- Hide created time by default
=> feat: Add more columns to workflows table + persistent filters

frontend/src/components/registry/icons.tsx, frontend/src/components/registry/registry-actions-table.tsx, frontend/src/components/workbench/panel/action-panel.tsx
- Add action icons
- Add icons + label for udf/template
=> feat(ui): Show action icons in registry table

frontend/src/components/json-viewer.tsx, frontend/src/components/workbench/events/events-workflow.tsx
- **Add margin for event input in left panel**
- **Remove badge for event time**
=> fix(ui): Fix some UI inconsistencies

.github/workflows/lint-python.yml, .github/workflows/test-pnpm-build.yml
Adds fine-grained permissions to all GH actions workflows
=> ci: Add permissions to all CICD actions

tests/unit/test_workflows.py, tracecat/dsl/common.py, tracecat/dsl/interceptor.py, tracecat/dsl/workflow.py, tracecat/workflow/executions/models.py
- Make `_get_trigger_type()` from interceptor into common; include in error info
- Include dsl title in error info
=> feat(engine): Include workflow title and trigger type in error handler

frontend/src/components/workbench/canvas/action-node.tsx
=> fix(ui): Fix child workflow icon when using ID

registry/tracecat_registry/integrations/ansible.py
Fixes: cannot read ssh key in Ansible integration.
Had to manually add `\n` newlines back into the ssh private key. Unfortunately the secrets manager does not preserve new lines currently. This is a temporary fix until we support different secret types.
=> fix(integrations): Ansible SSH

tracecat/dsl/workflow.py
=> feat(engine): Add trigger type to `ENV.workflow`

registry/tracecat_registry/templates/tools/okta/expire_password.yml, registry/tracecat_registry/templates/tools/okta/expire_password_with_temporary_password.yml, registry/tracecat_registry/templates/tools/okta/lookup_user_by_email.yml, registry/tracecat_registry/templates/tools/okta/reset_password.yml, registry/tracecat_registry/templates/tools/okta/suspend_user.yml
Adds the following actions for Okta:
- Suspend user
- Expire password
- Expire password with temporary password
- Reset password
N/A
Tested with an Okta tenant and all working.
Just a note, let me know if any of the naming needs to be changed for templates or inputs.
=> feat(integrations): Add password lifecycle Okta actions

tests/unit/test_auth_middleware.py, tracecat/api/app.py, tracecat/auth/credentials.py, tracecat/authz/service.py, tracecat/middleware/__init__.py, tracecat/middleware/auth.py
This PR introduces an `AuthorizationCacheMiddleware` that eliminates a **70.72x performance penalty** for basic users by caching workspace membership lookups within the scope of a single request.
Our performance tests revealed a critical bottleneck:
- **Admin users**: 0.01ms per authorization check (no DB queries needed)
- **Basic users**: 0.36ms per authorization check (requires membership DB query)
- **Slowdown factor**: 70.72x 🔥
While 0.35ms additional latency per request seems small, it compounds dramatically:
- 100 requests = 35ms additional overhead
- 1000 requests = 350ms additional overhead
- In busy systems, this leads to 5-8x overall slowdown
Every authorization check for unprivileged users queries the database to verify workspace membership. When multiple API endpoints are …
=> fix(api): Implement authz middleware to cache requests

tests/unit/test_secrets.py, tracecat/executor/service.py, tracecat/secrets/common.py
This PR addresses critical security vulnerabilities in the secrets masking system:
- **Problem**: Individual characters from secret values were being masked instead of complete secret values, causing output like `***h***e***l***l***o***` 
- **Root Cause**: `traverse_leaves(secrets)` extracted all leaf values, including individual characters
- **Fix**: Added length filtering (`len(secret_value) > 1`) in both collection and application layers
- **Impact**: Prevents information leakage about which characters are present in secrets
- **Problem**: Multiple logging statements could leak unmasked secrets
- **Locations Fixed**:
- `log.info("Run action", args=task.args)` - Could log templated secrets
- `logger.trace("Patched context", patched_context=patched_context)` - Logged entire context with …
=> fix(api): prevent over-aggressive character masking

tests/unit/test_organization_settings.py, tests/unit/test_repositories.py, tracecat/api/app.py, tracecat/git/constants.py, tracecat/git/utils.py, tracecat/registry/common.py, tracecat/registry/repositories/models.py, tracecat/settings/models.py
Fixes Git SSH URL validation and improves registry error handling to prevent startup failures.
**🔧 Git SSH URL Validation**
- Relaxed regex to support real-world patterns: custom ports, nested groups, optional  suffix
- Centralized validation logic across settings and repository models
- Examples now supported: , 
**🛡️ Registry Error Handling** 
- Registry loading failures no longer crash application startup
- Graceful error handling for repository creation/loading with warning logs
**✅ Tests**
- Comprehensive validation tests for Git settings
- Enhanced repository operation test coverage
-  - New constants and centralized validation
-  - Updated validation logic  
-  - Enhanced error handling
-  - New validation and repository tests
- Better compatibility with Git hosting providers
- …
=> fix: Relax git ssh url regex + restructure
